// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AuditEventOutcome.
const (
	Denied  AuditEventOutcome = "denied"
	Failed  AuditEventOutcome = "failed"
	Success AuditEventOutcome = "success"
)

// Valid indicates whether the value is a known member of the AuditEventOutcome enum.
func (e AuditEventOutcome) Valid() bool {
	switch e {
	case Denied:
		return true
	case Failed:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for ChannelName.
const (
	ChannelNameCandidate ChannelName = "candidate"
	ChannelNameStable    ChannelName = "stable"
)

// Valid indicates whether the value is a known member of the ChannelName enum.
func (e ChannelName) Valid() bool {
	switch e {
	case ChannelNameCandidate:
		return true
	case ChannelNameStable:
		return true
	default:
		return false
	}
}

// Defines values for ChannelRevisionChannel.
const (
	ChannelRevisionChannelCandidate ChannelRevisionChannel = "candidate"
	ChannelRevisionChannelStable    ChannelRevisionChannel = "stable"
)

// Valid indicates whether the value is a known member of the ChannelRevisionChannel enum.
func (e ChannelRevisionChannel) Valid() bool {
	switch e {
	case ChannelRevisionChannelCandidate:
		return true
	case ChannelRevisionChannelStable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok    HealthStatus = "ok"
	Ready HealthStatus = "ready"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for PackageChannels.
const (
	Candidate PackageChannels = "candidate"
	Stable    PackageChannels = "stable"
)

// Valid indicates whether the value is a known member of the PackageChannels enum.
func (e PackageChannels) Valid() bool {
	switch e {
	case Candidate:
		return true
	case Stable:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseState.
const (
	Draft         ReleaseState = "draft"
	PublishFailed ReleaseState = "publish_failed"
	Published     ReleaseState = "published"
	Publishing    ReleaseState = "publishing"
)

// Valid indicates whether the value is a known member of the ReleaseState enum.
func (e ReleaseState) Valid() bool {
	switch e {
	case Draft:
		return true
	case PublishFailed:
		return true
	case Published:
		return true
	case Publishing:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	Admin          Scope = "admin"
	ArtifactRead   Scope = "artifact:read"
	ArtifactWrite  Scope = "artifact:write"
	ChannelPromote Scope = "channel:promote"
	ReleasePublish Scope = "release:publish"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case Admin:
		return true
	case ArtifactRead:
		return true
	case ArtifactWrite:
		return true
	case ChannelPromote:
		return true
	case ReleasePublish:
		return true
	default:
		return false
	}
}

// AddReleaseArtifactRequest defines model for AddReleaseArtifactRequest.
type AddReleaseArtifactRequest struct {
	Arch         Coordinate          `json:"arch"`
	ArtifactPath string              `json:"artifactPath"`
	Os           Coordinate          `json:"os"`
	Role         *OptionalCoordinate `json:"role,omitempty"`
	Variant      *OptionalCoordinate `json:"variant,omitempty"`
}

// Artifact defines model for Artifact.
type Artifact struct {
	CreatedAt  Timestamp              `json:"createdAt"`
	CreatedBy  UUID                   `json:"createdBy"`
	Filename   string                 `json:"filename"`
	Id         UUID                   `json:"id"`
	MediaType  string                 `json:"mediaType"`
	Path       string                 `json:"path"`
	Properties map[string]interface{} `json:"properties"`
	Repository Name                   `json:"repository"`
	Sha256     Sha256                 `json:"sha256"`
	Size       int64                  `json:"size"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action       string                  `json:"action"`
	ActorId      *UUID                   `json:"actorId,omitempty"`
	Code         *string                 `json:"code,omitempty"`
	CreatedAt    Timestamp               `json:"createdAt"`
	Details      *map[string]interface{} `json:"details,omitempty"`
	Id           UUID                    `json:"id"`
	Outcome      AuditEventOutcome       `json:"outcome"`
	RepositoryId *UUID                   `json:"repositoryId,omitempty"`
	RequestId    string                  `json:"requestId"`
	ResourceId   *string                 `json:"resourceId,omitempty"`
	ResourceType string                  `json:"resourceType"`
}

// AuditEventOutcome defines model for AuditEvent.Outcome.
type AuditEventOutcome string

// AuditEventPage defines model for AuditEventPage.
type AuditEventPage struct {
	Items      []AuditEvent `json:"items"`
	NextCursor *PageCursor  `json:"nextCursor"`
}

// Channel defines model for Channel.
type Channel struct {
	CreatedAt      Timestamp   `json:"createdAt"`
	CurrentVersion *Version    `json:"currentVersion,omitempty"`
	Id             UUID        `json:"id"`
	Name           ChannelName `json:"name"`
	Package        Name        `json:"package"`
	Repository     Name        `json:"repository"`
}

// ChannelName defines model for Channel.Name.
type ChannelName string

// ChannelRevision defines model for ChannelRevision.
type ChannelRevision struct {
	ActorId     UUID                   `json:"actorId"`
	Channel     ChannelRevisionChannel `json:"channel"`
	CreatedAt   Timestamp              `json:"createdAt"`
	FromVersion *Version               `json:"fromVersion,omitempty"`
	Id          UUID                   `json:"id"`
	Reason      string                 `json:"reason"`
	RequestId   string                 `json:"requestId"`
	ToVersion   Version                `json:"toVersion"`
}

// ChannelRevisionChannel defines model for ChannelRevision.Channel.
type ChannelRevisionChannel string

// ChannelRevisionPage defines model for ChannelRevisionPage.
type ChannelRevisionPage struct {
	Items      []ChannelRevision `json:"items"`
	NextCursor *PageCursor       `json:"nextCursor"`
}

// Coordinate defines model for Coordinate.
type Coordinate = string

// CreatePackageRequest defines model for CreatePackageRequest.
type CreatePackageRequest struct {
	Name Name `json:"name"`
}

// CreateReleaseRequest defines model for CreateReleaseRequest.
type CreateReleaseRequest struct {
	Version Version `json:"version"`
}

// CreateRepositoryRequest defines model for CreateRepositoryRequest.
type CreateRepositoryRequest struct {
	DisplayName string `json:"displayName"`
	Key         Name   `json:"key"`
}

// CreateServiceAccountRequest defines model for CreateServiceAccountRequest.
type CreateServiceAccountRequest struct {
	Name ServiceAccountName `json:"name"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	ExpiresAt    Timestamp `json:"expiresAt"`
	Repositories []Name    `json:"repositories"`
	Scopes       []Scope   `json:"scopes"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// IssuedToken defines model for IssuedToken.
type IssuedToken struct {
	CreatedAt        Timestamp  `json:"createdAt"`
	ExpiresAt        Timestamp  `json:"expiresAt"`
	Id               UUID       `json:"id"`
	LastUsedAt       *Timestamp `json:"lastUsedAt,omitempty"`
	Repositories     []Name     `json:"repositories"`
	Revoked          bool       `json:"revoked"`
	Scopes           []Scope    `json:"scopes"`
	Secret           string     `json:"secret"`
	ServiceAccountId UUID       `json:"serviceAccountId"`
}

// Name defines model for Name.
type Name = string

// OptionalCoordinate defines model for OptionalCoordinate.
type OptionalCoordinate = string

// Package defines model for Package.
type Package struct {
	Channels   []PackageChannels `json:"channels"`
	CreatedAt  Timestamp         `json:"createdAt"`
	Id         UUID              `json:"id"`
	Name       Name              `json:"name"`
	Repository Name              `json:"repository"`
}

// PackageChannels defines model for Package.Channels.
type PackageChannels string

// PackagePage defines model for PackagePage.
type PackagePage struct {
	Items      []Package   `json:"items"`
	NextCursor *PageCursor `json:"nextCursor"`
}

// PageCursor defines model for PageCursor.
type PageCursor = string

// Problem defines model for Problem.
type Problem struct {
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	RequestId string  `json:"requestId"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// PromoteChannelRequest defines model for PromoteChannelRequest.
type PromoteChannelRequest struct {
	Reason  string  `json:"reason"`
	Version Version `json:"version"`
}

// Release defines model for Release.
type Release struct {
	Artifacts   []ReleaseArtifact `json:"artifacts"`
	CreatedAt   Timestamp         `json:"createdAt"`
	FailureCode *string           `json:"failureCode,omitempty"`
	Id          UUID              `json:"id"`
	Package     Name              `json:"package"`
	PublishedAt *Timestamp        `json:"publishedAt,omitempty"`
	Repository  Name              `json:"repository"`
	State       ReleaseState      `json:"state"`
	Version     Version           `json:"version"`
}

// ReleaseArtifact defines model for ReleaseArtifact.
type ReleaseArtifact struct {
	Arch     Coordinate         `json:"arch"`
	Artifact Artifact           `json:"artifact"`
	Id       UUID               `json:"id"`
	Os       Coordinate         `json:"os"`
	Role     OptionalCoordinate `json:"role"`
	Variant  OptionalCoordinate `json:"variant"`
}

// ReleaseManifest defines model for ReleaseManifest.
type ReleaseManifest struct {
	KeyId          string  `json:"keyId"`
	Manifest       string  `json:"manifest"`
	ManifestSha256 Sha256  `json:"manifestSha256"`
	Signature      string  `json:"signature"`
	Version        Version `json:"version"`
}

// ReleasePage defines model for ReleasePage.
type ReleasePage struct {
	Items      []Release   `json:"items"`
	NextCursor *PageCursor `json:"nextCursor"`
}

// ReleaseState defines model for ReleaseState.
type ReleaseState string

// Repository defines model for Repository.
type Repository struct {
	CreatedAt   Timestamp `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Id          UUID      `json:"id"`
	Key         Name      `json:"key"`
	Type        string    `json:"type"`
}

// RepositoryPage defines model for RepositoryPage.
type RepositoryPage struct {
	Items      []Repository `json:"items"`
	NextCursor *PageCursor  `json:"nextCursor"`
}

// ResolveArtifact defines model for ResolveArtifact.
type ResolveArtifact struct {
	Arch    Coordinate         `json:"arch"`
	Os      Coordinate         `json:"os"`
	Path    string             `json:"path"`
	Role    OptionalCoordinate `json:"role"`
	Sha256  Sha256             `json:"sha256"`
	Size    int64              `json:"size"`
	Variant OptionalCoordinate `json:"variant"`
}

// ResolveResponse defines model for ResolveResponse.
type ResolveResponse struct {
	Artifact    ResolveArtifact `json:"artifact"`
	DownloadUrl string          `json:"downloadUrl"`
	KeyId       string          `json:"keyId"`
	Manifest    string          `json:"manifest"`
	Signature   string          `json:"signature"`
	Version     Version         `json:"version"`
}

// Scope defines model for Scope.
type Scope string

// ServiceAccount defines model for ServiceAccount.
type ServiceAccount struct {
	CreatedAt Timestamp          `json:"createdAt"`
	Id        UUID               `json:"id"`
	Name      ServiceAccountName `json:"name"`
}

// ServiceAccountName defines model for ServiceAccountName.
type ServiceAccountName = string

// ServiceAccountPage defines model for ServiceAccountPage.
type ServiceAccountPage struct {
	Items      []ServiceAccount `json:"items"`
	NextCursor *PageCursor      `json:"nextCursor"`
}

// Sha256 defines model for Sha256.
type Sha256 = string

// SigningKey defines model for SigningKey.
type SigningKey struct {
	Active      bool      `json:"active"`
	Algorithm   string    `json:"algorithm"`
	CreatedAt   Timestamp `json:"createdAt"`
	Fingerprint Sha256    `json:"fingerprint"`
	KeyId       string    `json:"keyId"`
	PublicKey   string    `json:"publicKey"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// Token defines model for Token.
type Token struct {
	CreatedAt        Timestamp  `json:"createdAt"`
	ExpiresAt        Timestamp  `json:"expiresAt"`
	Id               UUID       `json:"id"`
	LastUsedAt       *Timestamp `json:"lastUsedAt,omitempty"`
	Repositories     []Name     `json:"repositories"`
	Revoked          bool       `json:"revoked"`
	Scopes           []Scope    `json:"scopes"`
	ServiceAccountId UUID       `json:"serviceAccountId"`
}

// TokenPage defines model for TokenPage.
type TokenPage struct {
	Items      []Token     `json:"items"`
	NextCursor *PageCursor `json:"nextCursor"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// Version defines model for Version.
type Version = string

// ArtifactPathParameter defines model for ArtifactPath.
type ArtifactPathParameter = string

// ArtifactPropertiesHeaderParameter defines model for ArtifactProperties.
type ArtifactPropertiesHeaderParameter = string

// ChannelPathParameter defines model for ChannelName.
type ChannelPathParameter = Name

// ChecksumDeployHeaderParameter defines model for ChecksumDeploy.
type ChecksumDeployHeaderParameter = bool

// ChecksumSha256HeaderParameter defines model for ChecksumSha256.
type ChecksumSha256HeaderParameter = Sha256

// ContentLengthHeaderParameter defines model for ContentLength.
type ContentLengthHeaderParameter = int64

// CursorQueryParameter defines model for Cursor.
type CursorQueryParameter = string

// IdempotencyKeyHeaderParameter defines model for IdempotencyKey.
type IdempotencyKeyHeaderParameter = string

// KeyIDPathParameter defines model for KeyID.
type KeyIDPathParameter = string

// LimitQueryParameter defines model for Limit.
type LimitQueryParameter = int

// PackagePathParameter defines model for PackageName.
type PackagePathParameter = Name

// RangeHeaderParameter defines model for Range.
type RangeHeaderParameter = string

// RedirectQueryParameter defines model for Redirect.
type RedirectQueryParameter = bool

// ReleaseArtifactIDPathParameter defines model for ReleaseArtifactID.
type ReleaseArtifactIDPathParameter = openapi_types.UUID

// RepoPathParameter defines model for Repo.
type RepoPathParameter = Name

// ServiceAccountIDPathParameter defines model for ServiceAccountID.
type ServiceAccountIDPathParameter = openapi_types.UUID

// TokenIDPathParameter defines model for TokenID.
type TokenIDPathParameter = openapi_types.UUID

// VersionPathParameter defines model for Version.
type VersionPathParameter = Version

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Conflict defines model for Conflict.
type Conflict = Problem

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InternalError defines model for InternalError.
type InternalError = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Problem

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// Unprocessable defines model for Unprocessable.
type Unprocessable = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListRepositoriesParams defines parameters for ListRepositories.
type ListRepositoriesParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateRepositoryParams defines parameters for CreateRepository.
type CreateRepositoryParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// GetArtifactParams defines parameters for GetArtifact.
type GetArtifactParams struct {
	RedirectQueryParameter *RedirectQueryParameter `form:"redirect,omitempty" json:"redirect,omitempty"`
	RangeHeaderParameter   *RangeHeaderParameter   `json:"Range,omitempty"`
}

// PutArtifactParams defines parameters for PutArtifact.
type PutArtifactParams struct {
	ContentLengthHeaderParameter  ContentLengthHeaderParameter   `json:"Content-Length"`
	ChecksumSha256HeaderParameter *ChecksumSha256HeaderParameter `json:"X-Checksum-Sha256,omitempty"`
	ChecksumDeployHeaderParameter *ChecksumDeployHeaderParameter `json:"X-Checksum-Deploy,omitempty"`

	// ArtifactPropertiesHeaderParameter Base64URL-encoded UTF-8 JSON Object, decoded maximum 16 KiB.
	ArtifactPropertiesHeaderParameter *ArtifactPropertiesHeaderParameter `json:"X-Artifact-Properties,omitempty"`
}

// ListPackagesParams defines parameters for ListPackages.
type ListPackagesParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePackageParams defines parameters for CreatePackage.
type CreatePackageParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// GetChannelHistoryParams defines parameters for GetChannelHistory.
type GetChannelHistoryParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// PromoteChannelParams defines parameters for PromoteChannel.
type PromoteChannelParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// ResolveChannelParams defines parameters for ResolveChannel.
type ResolveChannelParams struct {
	Os                     Coordinate              `form:"os" json:"os"`
	Arch                   Coordinate              `form:"arch" json:"arch"`
	Variant                *OptionalCoordinate     `form:"variant,omitempty" json:"variant,omitempty"`
	Role                   *OptionalCoordinate     `form:"role,omitempty" json:"role,omitempty"`
	RedirectQueryParameter *RedirectQueryParameter `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// ListReleasesParams defines parameters for ListReleases.
type ListReleasesParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateReleaseParams defines parameters for CreateRelease.
type CreateReleaseParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// CancelReleaseParams defines parameters for CancelRelease.
type CancelReleaseParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// AddReleaseArtifactParams defines parameters for AddReleaseArtifact.
type AddReleaseArtifactParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// RemoveReleaseArtifactParams defines parameters for RemoveReleaseArtifact.
type RemoveReleaseArtifactParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// PublishReleaseParams defines parameters for PublishRelease.
type PublishReleaseParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// ListServiceAccountsParams defines parameters for ListServiceAccounts.
type ListServiceAccountsParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateServiceAccountParams defines parameters for CreateServiceAccount.
type CreateServiceAccountParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	CursorQueryParameter *CursorQueryParameter `form:"cursor,omitempty" json:"cursor,omitempty"`
	LimitQueryParameter  *LimitQueryParameter  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTokenParams defines parameters for CreateToken.
type CreateTokenParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// RevokeTokenParams defines parameters for RevokeToken.
type RevokeTokenParams struct {
	IdempotencyKeyHeaderParameter *IdempotencyKeyHeaderParameter `json:"Idempotency-Key,omitempty"`
}

// CreateRepositoryJSONRequestBody defines body for CreateRepository for application/json ContentType.
type CreateRepositoryJSONRequestBody = CreateRepositoryRequest

// CreatePackageJSONRequestBody defines body for CreatePackage for application/json ContentType.
type CreatePackageJSONRequestBody = CreatePackageRequest

// PromoteChannelJSONRequestBody defines body for PromoteChannel for application/json ContentType.
type PromoteChannelJSONRequestBody = PromoteChannelRequest

// CreateReleaseJSONRequestBody defines body for CreateRelease for application/json ContentType.
type CreateReleaseJSONRequestBody = CreateReleaseRequest

// AddReleaseArtifactJSONRequestBody defines body for AddReleaseArtifact for application/json ContentType.
type AddReleaseArtifactJSONRequestBody = AddReleaseArtifactRequest

// CreateServiceAccountJSONRequestBody defines body for CreateServiceAccount for application/json ContentType.
type CreateServiceAccountJSONRequestBody = CreateServiceAccountRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest
