fullnameOverride: forge-dependencies

postgresql:
  fullnameOverride: forge-postgresql
  image: postgres:17-alpine
  database: artifact
  username: artifact
  password: CHANGE_ME
  storage:
    size: 2Gi
    storageClassName: ""
