apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifact-repository-local.fullname" . }}-minio
  labels:
    {{- include "artifact-repository-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  selector:
    {{- include "artifact-repository-local.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "artifact-repository-local.fullname" . }}-minio
  labels:
    {{- include "artifact-repository-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.minio.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "artifact-repository-local.fullname" . }}-minio
  labels:
    {{- include "artifact-repository-local.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "artifact-repository-local.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "artifact-repository-local.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          imagePullPolicy: IfNotPresent
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "artifact-repository-local.fullname" . }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "artifact-repository-local.fullname" . }}
                  key: MINIO_ROOT_PASSWORD
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "artifact-repository-local.fullname" . }}-minio
