apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-repository-local.fullname" . }}
  labels:
    {{- include "artifact-repository-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "postgresql.password is required" .Values.postgresql.password | quote }}
  MINIO_ROOT_USER: {{ required "minio.accessKey is required" .Values.minio.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ required "minio.secretKey is required" .Values.minio.secretKey | quote }}
