apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-repository-local.fullname" . }}
  labels:
    {{- include "artifact-repository-local.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ required "postgresql.password is required" .Values.postgresql.password | b64enc | quote }}
