// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredUploadSession = `-- name: ClaimExpiredUploadSession :one
UPDATE upload_sessions AS claimed
SET lease_owner = $1::uuid,
    lease_generation = claimed.lease_generation + 1,
    lease_expires_at = $2::timestamptz,
    last_heartbeat_at = $3::timestamptz
WHERE claimed.id = (
    SELECT candidate.id
    FROM upload_sessions AS candidate
    WHERE candidate.state IN ('active', 'failed')
      AND candidate.cleanup_completed_at IS NULL
      AND candidate.lease_expires_at < $3::timestamptz
      AND candidate.hard_deadline < $3::timestamptz
    ORDER BY candidate.hard_deadline, candidate.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, repository_id, logical_path, staging_key, state, lease_owner, lease_generation, lease_expires_at, hard_deadline, last_heartbeat_at, sha256, size, cleanup_completed_at, created_by, created_at, completed_at
`

type ClaimExpiredUploadSessionParams struct {
	LeaseOwner     uuid.UUID          `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Now            pgtype.Timestamptz `json:"now"`
}

func (q *Queries) ClaimExpiredUploadSession(ctx context.Context, arg ClaimExpiredUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, claimExpiredUploadSession, arg.LeaseOwner, arg.LeaseExpiresAt, arg.Now)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.LogicalPath,
		&i.StagingKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.HardDeadline,
		&i.LastHeartbeatAt,
		&i.Sha256,
		&i.Size,
		&i.CleanupCompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeUploadCleanup = `-- name: CompleteUploadCleanup :execrows
UPDATE upload_sessions
SET state = 'failed',
    cleanup_completed_at = $4
WHERE id = $1
  AND state IN ('active', 'failed')
  AND cleanup_completed_at IS NULL
  AND lease_owner = $2
  AND lease_generation = $3
`

type CompleteUploadCleanupParams struct {
	ID                 uuid.UUID          `json:"id"`
	LeaseOwner         uuid.UUID          `json:"lease_owner"`
	LeaseGeneration    int64              `json:"lease_generation"`
	CleanupCompletedAt pgtype.Timestamptz `json:"cleanup_completed_at"`
}

func (q *Queries) CompleteUploadCleanup(ctx context.Context, arg CompleteUploadCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeUploadCleanup,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.CleanupCompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeUploadSession = `-- name: CompleteUploadSession :execrows
UPDATE upload_sessions
SET state = 'completed',
    sha256 = $4,
    size = $5,
    completed_at = $6,
    cleanup_completed_at = $6
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type CompleteUploadSessionParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	Sha256          *string            `json:"sha256"`
	Size            *int64             `json:"size"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeUploadSession,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.Sha256,
		arg.Size,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    repository_id,
    logical_path,
    blob_sha256,
    media_type,
    filename,
    properties,
    created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, repository_id, logical_path, blob_sha256, media_type, filename, properties, created_by, created_at
`

type CreateArtifactParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	LogicalPath  string    `json:"logical_path"`
	BlobSha256   string    `json:"blob_sha256"`
	MediaType    string    `json:"media_type"`
	Filename     string    `json:"filename"`
	Properties   []byte    `json:"properties"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.RepositoryID,
		arg.LogicalPath,
		arg.BlobSha256,
		arg.MediaType,
		arg.Filename,
		arg.Properties,
		arg.CreatedBy,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.LogicalPath,
		&i.BlobSha256,
		&i.MediaType,
		&i.Filename,
		&i.Properties,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO upload_sessions (
    id,
    repository_id,
    logical_path,
    staging_key,
    state,
    lease_owner,
    lease_generation,
    lease_expires_at,
    hard_deadline,
    last_heartbeat_at,
    created_by
) VALUES ($1, $2, $3, $4, 'active', $5, 0, $6, $7, $8, $9)
RETURNING id, repository_id, logical_path, staging_key, state, lease_owner, lease_generation, lease_expires_at, hard_deadline, last_heartbeat_at, sha256, size, cleanup_completed_at, created_by, created_at, completed_at
`

type CreateUploadSessionParams struct {
	ID              uuid.UUID          `json:"id"`
	RepositoryID    uuid.UUID          `json:"repository_id"`
	LogicalPath     string             `json:"logical_path"`
	StagingKey      string             `json:"staging_key"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	HardDeadline    pgtype.Timestamptz `json:"hard_deadline"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.ID,
		arg.RepositoryID,
		arg.LogicalPath,
		arg.StagingKey,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.HardDeadline,
		arg.LastHeartbeatAt,
		arg.CreatedBy,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.LogicalPath,
		&i.StagingKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.HardDeadline,
		&i.LastHeartbeatAt,
		&i.Sha256,
		&i.Size,
		&i.CleanupCompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteFencedBlob = `-- name: DeleteFencedBlob :execrows
DELETE FROM blobs
WHERE sha256 = $1
  AND state = 'deleting'
  AND lease_owner = $2
  AND lease_generation = $3
`

type DeleteFencedBlobParams struct {
	Sha256          string     `json:"sha256"`
	LeaseOwner      *uuid.UUID `json:"lease_owner"`
	LeaseGeneration int64      `json:"lease_generation"`
}

func (q *Queries) DeleteFencedBlob(ctx context.Context, arg DeleteFencedBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFencedBlob, arg.Sha256, arg.LeaseOwner, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failUploadSession = `-- name: FailUploadSession :execrows
UPDATE upload_sessions
SET state = 'failed'
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type FailUploadSessionParams struct {
	ID              uuid.UUID `json:"id"`
	LeaseOwner      uuid.UUID `json:"lease_owner"`
	LeaseGeneration int64     `json:"lease_generation"`
}

func (q *Queries) FailUploadSession(ctx context.Context, arg FailUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failUploadSession, arg.ID, arg.LeaseOwner, arg.LeaseGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findVisibleArtifactOutsideRepository = `-- name: FindVisibleArtifactOutsideRepository :one
SELECT a.repository_id
FROM artifacts a
WHERE a.logical_path = $1
  AND a.repository_id <> $2
  AND (
      cardinality($3::uuid[]) = 0
      OR a.repository_id = ANY($3::uuid[])
  )
LIMIT 1
`

type FindVisibleArtifactOutsideRepositoryParams struct {
	LogicalPath          string      `json:"logical_path"`
	TargetRepositoryID   uuid.UUID   `json:"target_repository_id"`
	VisibleRepositoryIds []uuid.UUID `json:"visible_repository_ids"`
}

func (q *Queries) FindVisibleArtifactOutsideRepository(ctx context.Context, arg FindVisibleArtifactOutsideRepositoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findVisibleArtifactOutsideRepository, arg.LogicalPath, arg.TargetRepositoryID, arg.VisibleRepositoryIds)
	var repository_id uuid.UUID
	err := row.Scan(&repository_id)
	return repository_id, err
}

const findVisibleBlobForChecksumDeploy = `-- name: FindVisibleBlobForChecksumDeploy :one
SELECT b.sha256, b.size, b.object_key, b.state, b.lease_owner, b.lease_generation, b.lease_expires_at, b.delete_completed_at, b.last_referenced_at, b.created_at, b.updated_at
FROM blobs b
WHERE b.sha256 = $1
  AND b.state = 'ready'
  AND EXISTS (
      SELECT 1
      FROM artifacts a
      WHERE a.blob_sha256 = b.sha256
        AND (
            cardinality($2::uuid[]) = 0
            OR a.repository_id = ANY($2::uuid[])
        )
  )
LIMIT 1
FOR UPDATE OF b
`

type FindVisibleBlobForChecksumDeployParams struct {
	Sha256               string      `json:"sha256"`
	VisibleRepositoryIds []uuid.UUID `json:"visible_repository_ids"`
}

func (q *Queries) FindVisibleBlobForChecksumDeploy(ctx context.Context, arg FindVisibleBlobForChecksumDeployParams) (Blob, error) {
	row := q.db.QueryRow(ctx, findVisibleBlobForChecksumDeploy, arg.Sha256, arg.VisibleRepositoryIds)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByPath = `-- name: GetArtifactByPath :one
SELECT a.id, a.repository_id, a.logical_path, a.blob_sha256, a.media_type, a.filename, a.properties, a.created_by, a.created_at, b.size, b.object_key, b.state AS blob_state
FROM artifacts a
JOIN blobs b ON b.sha256 = a.blob_sha256
WHERE a.repository_id = $1 AND a.logical_path = $2
`

type GetArtifactByPathParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	LogicalPath  string    `json:"logical_path"`
}

type GetArtifactByPathRow struct {
	ID           uuid.UUID          `json:"id"`
	RepositoryID uuid.UUID          `json:"repository_id"`
	LogicalPath  string             `json:"logical_path"`
	BlobSha256   string             `json:"blob_sha256"`
	MediaType    string             `json:"media_type"`
	Filename     string             `json:"filename"`
	Properties   []byte             `json:"properties"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Size         int64              `json:"size"`
	ObjectKey    string             `json:"object_key"`
	BlobState    string             `json:"blob_state"`
}

func (q *Queries) GetArtifactByPath(ctx context.Context, arg GetArtifactByPathParams) (GetArtifactByPathRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByPath, arg.RepositoryID, arg.LogicalPath)
	var i GetArtifactByPathRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.LogicalPath,
		&i.BlobSha256,
		&i.MediaType,
		&i.Filename,
		&i.Properties,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Size,
		&i.ObjectKey,
		&i.BlobState,
	)
	return i, err
}

const getBlobForUpdate = `-- name: GetBlobForUpdate :one
SELECT sha256, size, object_key, state, lease_owner, lease_generation, lease_expires_at, delete_completed_at, last_referenced_at, created_at, updated_at FROM blobs WHERE sha256 = $1 FOR UPDATE
`

func (q *Queries) GetBlobForUpdate(ctx context.Context, sha256 string) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlobForUpdate, sha256)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPendingUploadSessionForStagingKey = `-- name: HasPendingUploadSessionForStagingKey :one
SELECT EXISTS (
    SELECT 1
    FROM upload_sessions
    WHERE staging_key = $1
      AND cleanup_completed_at IS NULL
)
`

func (q *Queries) HasPendingUploadSessionForStagingKey(ctx context.Context, stagingKey string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingUploadSessionForStagingKey, stagingKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeatUploadSession = `-- name: HeartbeatUploadSession :execrows
UPDATE upload_sessions
SET lease_expires_at = $4,
    last_heartbeat_at = $5
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type HeartbeatUploadSessionParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

func (q *Queries) HeartbeatUploadSession(ctx context.Context, arg HeartbeatUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatUploadSession,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.LeaseExpiresAt,
		arg.LastHeartbeatAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCreatingBlob = `-- name: InsertCreatingBlob :one
INSERT INTO blobs (
    sha256,
    size,
    object_key,
    state,
    lease_owner,
    lease_generation,
    lease_expires_at
) VALUES ($1, $2, $3, 'creating', $4, 0, $5)
ON CONFLICT (sha256) DO NOTHING
RETURNING sha256, size, object_key, state, lease_owner, lease_generation, lease_expires_at, delete_completed_at, last_referenced_at, created_at, updated_at
`

type InsertCreatingBlobParams struct {
	Sha256         string             `json:"sha256"`
	Size           int64              `json:"size"`
	ObjectKey      string             `json:"object_key"`
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) InsertCreatingBlob(ctx context.Context, arg InsertCreatingBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, insertCreatingBlob,
		arg.Sha256,
		arg.Size,
		arg.ObjectKey,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredUploadSessions = `-- name: ListExpiredUploadSessions :many
SELECT id, repository_id, logical_path, staging_key, state, lease_owner, lease_generation, lease_expires_at, hard_deadline, last_heartbeat_at, sha256, size, cleanup_completed_at, created_by, created_at, completed_at
FROM upload_sessions
WHERE state = 'active'
  AND lease_expires_at < $1
  AND hard_deadline < $1
ORDER BY hard_deadline
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredUploadSessionsParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListExpiredUploadSessions(ctx context.Context, arg ListExpiredUploadSessionsParams) ([]UploadSession, error) {
	rows, err := q.db.Query(ctx, listExpiredUploadSessions, arg.LeaseExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.LogicalPath,
			&i.StagingKey,
			&i.State,
			&i.LeaseOwner,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.HardDeadline,
			&i.LastHeartbeatAt,
			&i.Sha256,
			&i.Size,
			&i.CleanupCompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlobReady = `-- name: MarkBlobReady :one
UPDATE blobs
SET state = 'ready',
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $4
WHERE sha256 = $1
  AND state = 'creating'
  AND lease_owner = $2
  AND lease_generation = $3
RETURNING sha256, size, object_key, state, lease_owner, lease_generation, lease_expires_at, delete_completed_at, last_referenced_at, created_at, updated_at
`

type MarkBlobReadyParams struct {
	Sha256          string             `json:"sha256"`
	LeaseOwner      *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkBlobReady(ctx context.Context, arg MarkBlobReadyParams) (Blob, error) {
	row := q.db.QueryRow(ctx, markBlobReady,
		arg.Sha256,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.UpdatedAt,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrphanBlobDeleting = `-- name: MarkOrphanBlobDeleting :one
UPDATE blobs b
SET state = 'deleting',
    lease_owner = $2,
    lease_generation = lease_generation + 1,
    lease_expires_at = $3,
    delete_completed_at = NULL,
    updated_at = $4
WHERE b.sha256 = $1
  AND (
      b.state = 'ready'
      OR (b.state = 'creating' AND b.lease_expires_at < $4)
  )
  AND NOT EXISTS (SELECT 1 FROM artifacts a WHERE a.blob_sha256 = b.sha256)
  AND NOT EXISTS (
      SELECT 1 FROM release_manifests m
      WHERE m.manifest_blob_sha256 = b.sha256 OR m.signature_blob_sha256 = b.sha256
  )
RETURNING b.sha256, b.size, b.object_key, b.state, b.lease_owner, b.lease_generation, b.lease_expires_at, b.delete_completed_at, b.last_referenced_at, b.created_at, b.updated_at
`

type MarkOrphanBlobDeletingParams struct {
	Sha256         string             `json:"sha256"`
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkOrphanBlobDeleting(ctx context.Context, arg MarkOrphanBlobDeletingParams) (Blob, error) {
	row := q.db.QueryRow(ctx, markOrphanBlobDeleting,
		arg.Sha256,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takeExpiredCreatingBlob = `-- name: TakeExpiredCreatingBlob :one
UPDATE blobs
SET lease_owner = $2,
    lease_generation = lease_generation + 1,
    lease_expires_at = $3,
    updated_at = $4
WHERE sha256 = $1
  AND state = 'creating'
  AND lease_expires_at < $4
RETURNING sha256, size, object_key, state, lease_owner, lease_generation, lease_expires_at, delete_completed_at, last_referenced_at, created_at, updated_at
`

type TakeExpiredCreatingBlobParams struct {
	Sha256         string             `json:"sha256"`
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) TakeExpiredCreatingBlob(ctx context.Context, arg TakeExpiredCreatingBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, takeExpiredCreatingBlob,
		arg.Sha256,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchReadyBlob = `-- name: TouchReadyBlob :execrows
UPDATE blobs
SET last_referenced_at = $2,
    updated_at = $2
WHERE sha256 = $1
  AND state = 'ready'
`

type TouchReadyBlobParams struct {
	Sha256           string             `json:"sha256"`
	LastReferencedAt pgtype.Timestamptz `json:"last_referenced_at"`
}

func (q *Queries) TouchReadyBlob(ctx context.Context, arg TouchReadyBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchReadyBlob, arg.Sha256, arg.LastReferencedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
