// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :one
UPDATE idempotency_records
SET state = 'completed',
    http_status = $2,
    response_body = $3,
    response_encrypted = $4,
    completed_at = $5,
    updated_at = $5
WHERE id = $1
  AND state = 'pending'
RETURNING id, token_id, http_method, canonical_resource, idempotency_key, request_fingerprint, state, http_status, response_body, response_encrypted, expires_at, completed_at, created_at, updated_at
`

type CompleteIdempotencyRecordParams struct {
	ID                uuid.UUID          `json:"id"`
	HttpStatus        *int32             `json:"http_status"`
	ResponseBody      []byte             `json:"response_body"`
	ResponseEncrypted bool               `json:"response_encrypted"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyRecord,
		arg.ID,
		arg.HttpStatus,
		arg.ResponseBody,
		arg.ResponseEncrypted,
		arg.CompletedAt,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.HttpMethod,
		&i.CanonicalResource,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.ResponseEncrypted,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countServiceAccounts = `-- name: CountServiceAccounts :one
SELECT count(*) FROM service_accounts
`

func (q *Queries) CountServiceAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
	ID,
    service_account_id,
    secret_hmac,
    scopes,
    repository_ids,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_account_id, secret_hmac, scopes, repository_ids, expires_at, revoked_at, last_used_at, created_at
`

type CreateAPITokenParams struct {
	ID               uuid.UUID          `json:"id"`
	ServiceAccountID uuid.UUID          `json:"service_account_id"`
	SecretHmac       []byte             `json:"secret_hmac"`
	Scopes           []string           `json:"scopes"`
	RepositoryIds    []uuid.UUID        `json:"repository_ids"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.ServiceAccountID,
		arg.SecretHmac,
		arg.Scopes,
		arg.RepositoryIds,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.SecretHmac,
		&i.Scopes,
		&i.RepositoryIds,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    actor_token_id,
    repository_id,
    action,
    resource_type,
    resource_id,
    outcome,
    code,
    request_id,
    details
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, actor_token_id, repository_id, action, resource_type, resource_id, outcome, code, request_id, details, created_at
`

type CreateAuditEventParams struct {
	ActorTokenID *uuid.UUID `json:"actor_token_id"`
	RepositoryID *uuid.UUID `json:"repository_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *string    `json:"resource_id"`
	Outcome      string     `json:"outcome"`
	Code         *string    `json:"code"`
	RequestID    string     `json:"request_id"`
	Details      []byte     `json:"details"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ActorTokenID,
		arg.RepositoryID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Code,
		arg.RequestID,
		arg.Details,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorTokenID,
		&i.RepositoryID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Outcome,
		&i.Code,
		&i.RequestID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateServiceAccount(ctx context.Context, name string) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount, name)
	var i ServiceAccount
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
DELETE FROM idempotency_records
WHERE expires_at < $1
  AND state = 'completed'
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecords, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPITokenForAuthentication = `-- name: GetAPITokenForAuthentication :one
SELECT t.id, t.service_account_id, t.secret_hmac, t.scopes, t.repository_ids, t.expires_at, t.revoked_at, t.last_used_at, t.created_at, s.name AS service_account_name
FROM api_tokens t
JOIN service_accounts s ON s.id = t.service_account_id
WHERE t.id = $1
`

type GetAPITokenForAuthenticationRow struct {
	ID                 uuid.UUID          `json:"id"`
	ServiceAccountID   uuid.UUID          `json:"service_account_id"`
	SecretHmac         []byte             `json:"secret_hmac"`
	Scopes             []string           `json:"scopes"`
	RepositoryIds      []uuid.UUID        `json:"repository_ids"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ServiceAccountName string             `json:"service_account_name"`
}

func (q *Queries) GetAPITokenForAuthentication(ctx context.Context, id uuid.UUID) (GetAPITokenForAuthenticationRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenForAuthentication, id)
	var i GetAPITokenForAuthenticationRow
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.SecretHmac,
		&i.Scopes,
		&i.RepositoryIds,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ServiceAccountName,
	)
	return i, err
}

const getIdempotencyRecordForUpdate = `-- name: GetIdempotencyRecordForUpdate :one
SELECT id, token_id, http_method, canonical_resource, idempotency_key, request_fingerprint, state, http_status, response_body, response_encrypted, expires_at, completed_at, created_at, updated_at
FROM idempotency_records
WHERE token_id = $1
  AND http_method = $2
  AND canonical_resource = $3
  AND idempotency_key = $4
FOR UPDATE
`

type GetIdempotencyRecordForUpdateParams struct {
	TokenID           uuid.UUID `json:"token_id"`
	HttpMethod        string    `json:"http_method"`
	CanonicalResource string    `json:"canonical_resource"`
	IdempotencyKey    string    `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordForUpdate,
		arg.TokenID,
		arg.HttpMethod,
		arg.CanonicalResource,
		arg.IdempotencyKey,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.HttpMethod,
		&i.CanonicalResource,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.ResponseEncrypted,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceAccount = `-- name: GetServiceAccount :one
SELECT id, name, created_at FROM service_accounts WHERE id = $1
`

func (q *Queries) GetServiceAccount(ctx context.Context, id uuid.UUID) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, getServiceAccount, id)
	var i ServiceAccount
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT key_id, algorithm, public_key, fingerprint, active, created_at FROM signing_keys WHERE key_id = $1
`

func (q *Queries) GetSigningKey(ctx context.Context, keyID string) (SigningKey, error) {
	row := q.db.QueryRow(ctx, getSigningKey, keyID)
	var i SigningKey
	err := row.Scan(
		&i.KeyID,
		&i.Algorithm,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :one
INSERT INTO idempotency_records (
    token_id,
    http_method,
    canonical_resource,
    idempotency_key,
    request_fingerprint,
    state,
    expires_at
) VALUES ($1, $2, $3, $4, $5, 'pending', $6)
ON CONFLICT (token_id, http_method, canonical_resource, idempotency_key) DO NOTHING
RETURNING id, token_id, http_method, canonical_resource, idempotency_key, request_fingerprint, state, http_status, response_body, response_encrypted, expires_at, completed_at, created_at, updated_at
`

type InsertIdempotencyRecordParams struct {
	TokenID            uuid.UUID          `json:"token_id"`
	HttpMethod         string             `json:"http_method"`
	CanonicalResource  string             `json:"canonical_resource"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyRecord,
		arg.TokenID,
		arg.HttpMethod,
		arg.CanonicalResource,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ExpiresAt,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.HttpMethod,
		&i.CanonicalResource,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.HttpStatus,
		&i.ResponseBody,
		&i.ResponseEncrypted,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, service_account_id, secret_hmac, scopes, repository_ids, expires_at, revoked_at, last_used_at, created_at
FROM api_tokens
WHERE service_account_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < (
          $2::timestamptz,
          $3::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAPITokensParams struct {
	ServiceAccountID uuid.UUID          `json:"service_account_id"`
	AfterCreatedAt   pgtype.Timestamptz `json:"after_created_at"`
	AfterID          uuid.UUID          `json:"after_id"`
	PageLimit        int32              `json:"page_limit"`
}

func (q *Queries) ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens,
		arg.ServiceAccountID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.ServiceAccountID,
			&i.SecretHmac,
			&i.Scopes,
			&i.RepositoryIds,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_token_id, repository_id, action, resource_type, resource_id, outcome, code, request_id, details, created_at
FROM audit_events
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < (
        $1::timestamptz,
        $2::uuid
    )
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAuditEventsParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorTokenID,
			&i.RepositoryID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.Code,
			&i.RequestID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT id, name, created_at
FROM service_accounts
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < (
        $1::timestamptz,
        $2::uuid
    )
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListServiceAccountsParams struct {
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]ServiceAccount, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceAccount{}
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, $2)
WHERE id = $1
`

type RevokeAPITokenParams struct {
	ID        uuid.UUID          `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens
SET last_used_at = $1::timestamptz
WHERE id = $2::uuid
  AND (
      last_used_at IS NULL
      OR last_used_at < $1::timestamptz - interval '5 minutes'
  )
`

type TouchAPITokenParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}

const upsertSigningKey = `-- name: UpsertSigningKey :one
INSERT INTO signing_keys (key_id, algorithm, public_key, fingerprint, active)
VALUES ($1, 'Ed25519', $2, $3, $4)
ON CONFLICT (key_id) DO UPDATE
SET public_key = EXCLUDED.public_key,
    fingerprint = EXCLUDED.fingerprint,
    active = EXCLUDED.active
RETURNING key_id, algorithm, public_key, fingerprint, active, created_at
`

type UpsertSigningKeyParams struct {
	KeyID       string `json:"key_id"`
	PublicKey   []byte `json:"public_key"`
	Fingerprint string `json:"fingerprint"`
	Active      bool   `json:"active"`
}

func (q *Queries) UpsertSigningKey(ctx context.Context, arg UpsertSigningKeyParams) (SigningKey, error) {
	row := q.db.QueryRow(ctx, upsertSigningKey,
		arg.KeyID,
		arg.PublicKey,
		arg.Fingerprint,
		arg.Active,
	)
	var i SigningKey
	err := row.Scan(
		&i.KeyID,
		&i.Algorithm,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
