// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, package_id, name, current_release_id, created_at
FROM channels
WHERE package_id = $1 AND name = $2
`

type GetChannelByNameParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByName, arg.PackageID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.CurrentReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelForUpdate = `-- name: GetChannelForUpdate :one
SELECT id, package_id, name, current_release_id, created_at
FROM channels
WHERE package_id = $1 AND name = $2
FOR UPDATE
`

type GetChannelForUpdateParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetChannelForUpdate(ctx context.Context, arg GetChannelForUpdateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelForUpdate, arg.PackageID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.CurrentReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelHistory = `-- name: ListChannelHistory :many
SELECT cr.id, cr.package_id, cr.channel_id, cr.from_release_id, cr.to_release_id, cr.actor_token_id, cr.reason, cr.request_id, cr.created_at,
       previous.version AS from_version,
       target.version AS to_version
FROM channel_revisions cr
LEFT JOIN releases previous ON previous.id = cr.from_release_id
JOIN releases target ON target.id = cr.to_release_id
WHERE cr.channel_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (cr.created_at, cr.id) < (
          $2::timestamptz,
          $3::uuid
      )
  )
ORDER BY cr.created_at DESC, cr.id DESC
LIMIT $4
`

type ListChannelHistoryParams struct {
	ChannelID      uuid.UUID          `json:"channel_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

type ListChannelHistoryRow struct {
	ID            uuid.UUID          `json:"id"`
	PackageID     uuid.UUID          `json:"package_id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	FromReleaseID *uuid.UUID         `json:"from_release_id"`
	ToReleaseID   uuid.UUID          `json:"to_release_id"`
	ActorTokenID  uuid.UUID          `json:"actor_token_id"`
	Reason        string             `json:"reason"`
	RequestID     string             `json:"request_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FromVersion   *string            `json:"from_version"`
	ToVersion     string             `json:"to_version"`
}

func (q *Queries) ListChannelHistory(ctx context.Context, arg ListChannelHistoryParams) ([]ListChannelHistoryRow, error) {
	rows, err := q.db.Query(ctx, listChannelHistory,
		arg.ChannelID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelHistoryRow{}
	for rows.Next() {
		var i ListChannelHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.ChannelID,
			&i.FromReleaseID,
			&i.ToReleaseID,
			&i.ActorTokenID,
			&i.Reason,
			&i.RequestID,
			&i.CreatedAt,
			&i.FromVersion,
			&i.ToVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteChannel = `-- name: PromoteChannel :one
WITH previous AS (
    SELECT current_release_id
    FROM channels
    WHERE id = $1 AND package_id = $2
    FOR UPDATE
), updated AS (
    UPDATE channels
    SET current_release_id = $3
    WHERE id = $1 AND package_id = $2
    RETURNING id
)
INSERT INTO channel_revisions (
    package_id,
    channel_id,
    from_release_id,
    to_release_id,
    actor_token_id,
    reason,
    request_id
)
SELECT $2, $1, previous.current_release_id, $3, $4, $5, $6
FROM previous, updated
RETURNING id, package_id, channel_id, from_release_id, to_release_id, actor_token_id, reason, request_id, created_at
`

type PromoteChannelParams struct {
	ChannelID    uuid.UUID `json:"channel_id"`
	PackageID    uuid.UUID `json:"package_id"`
	ToReleaseID  uuid.UUID `json:"to_release_id"`
	ActorTokenID uuid.UUID `json:"actor_token_id"`
	Reason       string    `json:"reason"`
	RequestID    string    `json:"request_id"`
}

func (q *Queries) PromoteChannel(ctx context.Context, arg PromoteChannelParams) (ChannelRevision, error) {
	row := q.db.QueryRow(ctx, promoteChannel,
		arg.ChannelID,
		arg.PackageID,
		arg.ToReleaseID,
		arg.ActorTokenID,
		arg.Reason,
		arg.RequestID,
	)
	var i ChannelRevision
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.ChannelID,
		&i.FromReleaseID,
		&i.ToReleaseID,
		&i.ActorTokenID,
		&i.Reason,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const resolveChannelArtifact = `-- name: ResolveChannelArtifact :one
SELECT r.id AS release_id,
       r.version,
       rm.manifest_blob_sha256,
       rm.signature_blob_sha256,
       rm.key_id,
       manifest_blob.object_key AS manifest_object_key,
       signature_blob.object_key AS signature_object_key,
       signing_key.public_key,
       ra.id AS release_artifact_id,
       ra.os,
       ra.arch,
       ra.variant,
       ra.role,
       a.logical_path,
       a.blob_sha256,
       a.media_type,
       a.filename,
       b.size,
       b.object_key
FROM channels c
JOIN releases r ON r.id = c.current_release_id AND r.package_id = c.package_id
JOIN release_manifests rm ON rm.release_id = r.id
JOIN blobs manifest_blob ON manifest_blob.sha256 = rm.manifest_blob_sha256
JOIN blobs signature_blob ON signature_blob.sha256 = rm.signature_blob_sha256
JOIN signing_keys signing_key ON signing_key.key_id = rm.key_id
JOIN release_artifacts ra ON ra.release_id = r.id
JOIN artifacts a ON a.id = ra.artifact_id
JOIN blobs b ON b.sha256 = a.blob_sha256
WHERE c.package_id = $1
  AND c.name = $2
  AND ra.os = $3
  AND ra.arch = $4
  AND ra.variant = $5
  AND ra.role = $6
  AND r.state = 'published'
  AND b.state = 'ready'
  AND manifest_blob.state = 'ready'
  AND signature_blob.state = 'ready'
`

type ResolveChannelArtifactParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Name      string    `json:"name"`
	Os        string    `json:"os"`
	Arch      string    `json:"arch"`
	Variant   string    `json:"variant"`
	Role      string    `json:"role"`
}

type ResolveChannelArtifactRow struct {
	ReleaseID           uuid.UUID `json:"release_id"`
	Version             string    `json:"version"`
	ManifestBlobSha256  string    `json:"manifest_blob_sha256"`
	SignatureBlobSha256 string    `json:"signature_blob_sha256"`
	KeyID               string    `json:"key_id"`
	ManifestObjectKey   string    `json:"manifest_object_key"`
	SignatureObjectKey  string    `json:"signature_object_key"`
	PublicKey           []byte    `json:"public_key"`
	ReleaseArtifactID   uuid.UUID `json:"release_artifact_id"`
	Os                  string    `json:"os"`
	Arch                string    `json:"arch"`
	Variant             string    `json:"variant"`
	Role                string    `json:"role"`
	LogicalPath         string    `json:"logical_path"`
	BlobSha256          string    `json:"blob_sha256"`
	MediaType           string    `json:"media_type"`
	Filename            string    `json:"filename"`
	Size                int64     `json:"size"`
	ObjectKey           string    `json:"object_key"`
}

func (q *Queries) ResolveChannelArtifact(ctx context.Context, arg ResolveChannelArtifactParams) (ResolveChannelArtifactRow, error) {
	row := q.db.QueryRow(ctx, resolveChannelArtifact,
		arg.PackageID,
		arg.Name,
		arg.Os,
		arg.Arch,
		arg.Variant,
		arg.Role,
	)
	var i ResolveChannelArtifactRow
	err := row.Scan(
		&i.ReleaseID,
		&i.Version,
		&i.ManifestBlobSha256,
		&i.SignatureBlobSha256,
		&i.KeyID,
		&i.ManifestObjectKey,
		&i.SignatureObjectKey,
		&i.PublicKey,
		&i.ReleaseArtifactID,
		&i.Os,
		&i.Arch,
		&i.Variant,
		&i.Role,
		&i.LogicalPath,
		&i.BlobSha256,
		&i.MediaType,
		&i.Filename,
		&i.Size,
		&i.ObjectKey,
	)
	return i, err
}
