// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs AS claimed
SET state = 'running',
    attempts = claimed.attempts + 1,
    lease_owner = $2,
    lease_generation = claimed.lease_generation + 1,
    lease_expires_at = $3,
    updated_at = $4
WHERE claimed.id = (
    SELECT candidate.id
    FROM jobs AS candidate
    WHERE (
        candidate.state = 'pending'
        OR (candidate.state = 'running' AND candidate.lease_expires_at < $4)
    )
      AND candidate.available_at <= $4
      AND candidate.attempts < candidate.max_attempts
      AND candidate.kind = $1
    ORDER BY candidate.available_at, candidate.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, payload, state, attempts, max_attempts, lease_owner, lease_generation, lease_expires_at, available_at, failure_code, created_at, updated_at
`

type ClaimJobParams struct {
	Kind           string             `json:"kind"`
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob,
		arg.Kind,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimOrphanBlob = `-- name: ClaimOrphanBlob :one
UPDATE blobs AS claimed
SET state = 'deleting',
    lease_owner = $1,
    lease_generation = claimed.lease_generation + 1,
    lease_expires_at = $2,
    delete_completed_at = NULL,
    updated_at = $3
WHERE claimed.sha256 = (
    SELECT candidate.sha256
    FROM blobs AS candidate
    WHERE (
        (
            candidate.state = 'deleting'
            AND candidate.delete_completed_at IS NULL
            AND candidate.lease_expires_at < $3
        )
        OR (
            candidate.state = 'ready'
            AND COALESCE(candidate.last_referenced_at, candidate.created_at) < $4
        )
        OR (
            candidate.state = 'creating'
            AND candidate.lease_expires_at < $3
            AND candidate.created_at < $4
        )
    )
      AND NOT EXISTS (SELECT 1 FROM artifacts a WHERE a.blob_sha256 = candidate.sha256)
      AND NOT EXISTS (
          SELECT 1
          FROM release_manifests m
          WHERE m.manifest_blob_sha256 = candidate.sha256
             OR m.signature_blob_sha256 = candidate.sha256
      )
	  AND NOT EXISTS (
	      SELECT 1
	      FROM publish_attempts p
	      WHERE p.state = 'active'
	        AND (
	            p.manifest_sha256 = candidate.sha256
	            OR p.signature_sha256 = candidate.sha256
	        )
	  )
    ORDER BY candidate.created_at, candidate.sha256
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING claimed.sha256, claimed.size, claimed.object_key, claimed.state, claimed.lease_owner, claimed.lease_generation, claimed.lease_expires_at, claimed.delete_completed_at, claimed.last_referenced_at, claimed.created_at, claimed.updated_at
`

type ClaimOrphanBlobParams struct {
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Now            pgtype.Timestamptz `json:"now"`
	Cutoff         pgtype.Timestamptz `json:"cutoff"`
}

func (q *Queries) ClaimOrphanBlob(ctx context.Context, arg ClaimOrphanBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, claimOrphanBlob,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.Cutoff,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET state = 'completed',
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $4
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'running'
`

type CompleteJobParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQuarantinedBlob = `-- name: DeleteQuarantinedBlob :one
DELETE FROM blobs AS deleted
WHERE deleted.sha256 = (
    SELECT candidate.sha256
    FROM blobs AS candidate
    WHERE candidate.state = 'deleting'
      AND candidate.delete_completed_at IS NOT NULL
      AND candidate.lease_expires_at < $1
      AND NOT EXISTS (SELECT 1 FROM artifacts a WHERE a.blob_sha256 = candidate.sha256)
      AND NOT EXISTS (
          SELECT 1
          FROM release_manifests m
          WHERE m.manifest_blob_sha256 = candidate.sha256
             OR m.signature_blob_sha256 = candidate.sha256
      )
      AND NOT EXISTS (
          SELECT 1
          FROM publish_attempts p
          WHERE p.state = 'active'
            AND (
                p.manifest_sha256 = candidate.sha256
                OR p.signature_sha256 = candidate.sha256
            )
      )
    ORDER BY candidate.delete_completed_at, candidate.sha256
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING deleted.sha256, deleted.size, deleted.object_key, deleted.state, deleted.lease_owner, deleted.lease_generation, deleted.lease_expires_at, deleted.delete_completed_at, deleted.last_referenced_at, deleted.created_at, deleted.updated_at
`

func (q *Queries) DeleteQuarantinedBlob(ctx context.Context, now pgtype.Timestamptz) (Blob, error) {
	row := q.db.QueryRow(ctx, deleteQuarantinedBlob, now)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (kind, payload, state, max_attempts, available_at)
VALUES ($1, $2, 'pending', $3, $4)
ON CONFLICT (kind) WHERE state IN ('pending', 'running') DO NOTHING
RETURNING id, kind, payload, state, attempts, max_attempts, lease_owner, lease_generation, lease_expires_at, available_at, failure_code, created_at, updated_at
`

type EnqueueJobParams struct {
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	MaxAttempts int32              `json:"max_attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.Payload,
		arg.MaxAttempts,
		arg.AvailableAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.FailureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStorageOrphanBlobTombstone = `-- name: InsertStorageOrphanBlobTombstone :one
INSERT INTO blobs (
    sha256,
    size,
    object_key,
    state,
    lease_owner,
    lease_generation,
    lease_expires_at,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    'deleting',
    $4,
    0,
    $5,
    $6,
    $6
)
ON CONFLICT DO NOTHING
RETURNING sha256, size, object_key, state, lease_owner, lease_generation, lease_expires_at, delete_completed_at, last_referenced_at, created_at, updated_at
`

type InsertStorageOrphanBlobTombstoneParams struct {
	Sha256         string             `json:"sha256"`
	Size           int64              `json:"size"`
	ObjectKey      string             `json:"object_key"`
	LeaseOwner     *uuid.UUID         `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Now            pgtype.Timestamptz `json:"now"`
}

func (q *Queries) InsertStorageOrphanBlobTombstone(ctx context.Context, arg InsertStorageOrphanBlobTombstoneParams) (Blob, error) {
	row := q.db.QueryRow(ctx, insertStorageOrphanBlobTombstone,
		arg.Sha256,
		arg.Size,
		arg.ObjectKey,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.Now,
	)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.Size,
		&i.ObjectKey,
		&i.State,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.DeleteCompletedAt,
		&i.LastReferencedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBlobDeleteCompleted = `-- name: MarkBlobDeleteCompleted :execrows
UPDATE blobs
SET delete_completed_at = $4,
    lease_expires_at = $5,
    updated_at = $4
WHERE sha256 = $1
  AND state = 'deleting'
  AND delete_completed_at IS NULL
  AND lease_owner = $2
  AND lease_generation = $3
`

type MarkBlobDeleteCompletedParams struct {
	Sha256            string             `json:"sha256"`
	LeaseOwner        *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration   int64              `json:"lease_generation"`
	DeleteCompletedAt pgtype.Timestamptz `json:"delete_completed_at"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) MarkBlobDeleteCompleted(ctx context.Context, arg MarkBlobDeleteCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBlobDeleteCompleted,
		arg.Sha256,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.DeleteCompletedAt,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapExpiredExhaustedJob = `-- name: ReapExpiredExhaustedJob :execrows
UPDATE jobs
SET state = 'failed',
    failure_code = 'job-attempts-exhausted',
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $2
WHERE kind = $1
  AND state = 'running'
  AND lease_expires_at < $2
  AND attempts >= max_attempts
`

type ReapExpiredExhaustedJobParams struct {
	Kind      string             `json:"kind"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReapExpiredExhaustedJob(ctx context.Context, arg ReapExpiredExhaustedJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredExhaustedJob, arg.Kind, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewBlobDeleteLease = `-- name: RenewBlobDeleteLease :execrows
UPDATE blobs
SET lease_expires_at = $4,
    updated_at = $5
WHERE sha256 = $1
  AND state = 'deleting'
  AND delete_completed_at IS NULL
  AND lease_owner = $2
  AND lease_generation = $3
`

type RenewBlobDeleteLeaseParams struct {
	Sha256          string             `json:"sha256"`
	LeaseOwner      *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RenewBlobDeleteLease(ctx context.Context, arg RenewBlobDeleteLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewBlobDeleteLease,
		arg.Sha256,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,
    failure_code = $4,
    available_at = $5,
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $6
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'running'
`

type RetryJobParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	FailureCode     *string            `json:"failure_code"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.FailureCode,
		arg.AvailableAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
