// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID               uuid.UUID          `json:"id"`
	ServiceAccountID uuid.UUID          `json:"service_account_id"`
	SecretHmac       []byte             `json:"secret_hmac"`
	Scopes           []string           `json:"scopes"`
	RepositoryIds    []uuid.UUID        `json:"repository_ids"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Artifact struct {
	ID           uuid.UUID          `json:"id"`
	RepositoryID uuid.UUID          `json:"repository_id"`
	LogicalPath  string             `json:"logical_path"`
	BlobSha256   string             `json:"blob_sha256"`
	MediaType    string             `json:"media_type"`
	Filename     string             `json:"filename"`
	Properties   []byte             `json:"properties"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID           uuid.UUID          `json:"id"`
	ActorTokenID *uuid.UUID         `json:"actor_token_id"`
	RepositoryID *uuid.UUID         `json:"repository_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Outcome      string             `json:"outcome"`
	Code         *string            `json:"code"`
	RequestID    string             `json:"request_id"`
	Details      []byte             `json:"details"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Blob struct {
	Sha256            string             `json:"sha256"`
	Size              int64              `json:"size"`
	ObjectKey         string             `json:"object_key"`
	State             string             `json:"state"`
	LeaseOwner        *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration   int64              `json:"lease_generation"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	DeleteCompletedAt pgtype.Timestamptz `json:"delete_completed_at"`
	LastReferencedAt  pgtype.Timestamptz `json:"last_referenced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Channel struct {
	ID               uuid.UUID          `json:"id"`
	PackageID        uuid.UUID          `json:"package_id"`
	Name             string             `json:"name"`
	CurrentReleaseID *uuid.UUID         `json:"current_release_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ChannelRevision struct {
	ID            uuid.UUID          `json:"id"`
	PackageID     uuid.UUID          `json:"package_id"`
	ChannelID     uuid.UUID          `json:"channel_id"`
	FromReleaseID *uuid.UUID         `json:"from_release_id"`
	ToReleaseID   uuid.UUID          `json:"to_release_id"`
	ActorTokenID  uuid.UUID          `json:"actor_token_id"`
	Reason        string             `json:"reason"`
	RequestID     string             `json:"request_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyRecord struct {
	ID                 uuid.UUID          `json:"id"`
	TokenID            uuid.UUID          `json:"token_id"`
	HttpMethod         string             `json:"http_method"`
	CanonicalResource  string             `json:"canonical_resource"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint []byte             `json:"request_fingerprint"`
	State              string             `json:"state"`
	HttpStatus         *int32             `json:"http_status"`
	ResponseBody       []byte             `json:"response_body"`
	ResponseEncrypted  bool               `json:"response_encrypted"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID              uuid.UUID          `json:"id"`
	Kind            string             `json:"kind"`
	Payload         []byte             `json:"payload"`
	State           string             `json:"state"`
	Attempts        int32              `json:"attempts"`
	MaxAttempts     int32              `json:"max_attempts"`
	LeaseOwner      *uuid.UUID         `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	AvailableAt     pgtype.Timestamptz `json:"available_at"`
	FailureCode     *string            `json:"failure_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Package struct {
	ID           uuid.UUID          `json:"id"`
	RepositoryID uuid.UUID          `json:"repository_id"`
	Name         string             `json:"name"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PublishAttempt struct {
	ID                  uuid.UUID          `json:"id"`
	ReleaseID           uuid.UUID          `json:"release_id"`
	IdempotencyRecordID *uuid.UUID         `json:"idempotency_record_id"`
	ActorTokenID        uuid.UUID          `json:"actor_token_id"`
	RequestID           string             `json:"request_id"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	Snapshot            []byte             `json:"snapshot"`
	SnapshotSha256      string             `json:"snapshot_sha256"`
	KeyID               string             `json:"key_id"`
	LeaseOwner          uuid.UUID          `json:"lease_owner"`
	LeaseGeneration     int64              `json:"lease_generation"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
	State               string             `json:"state"`
	StorageCompleted    bool               `json:"storage_completed"`
	ManifestSha256      *string            `json:"manifest_sha256"`
	SignatureSha256     *string            `json:"signature_sha256"`
	FailureCode         *string            `json:"failure_code"`
	RetryCount          int32              `json:"retry_count"`
	NextRetryAt         pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Release struct {
	ID               uuid.UUID          `json:"id"`
	PackageID        uuid.UUID          `json:"package_id"`
	Version          string             `json:"version"`
	State            string             `json:"state"`
	CurrentAttemptID *uuid.UUID         `json:"current_attempt_id"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	FailureCode      *string            `json:"failure_code"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ReleaseArtifact struct {
	ID         uuid.UUID          `json:"id"`
	ReleaseID  uuid.UUID          `json:"release_id"`
	ArtifactID uuid.UUID          `json:"artifact_id"`
	Os         string             `json:"os"`
	Arch       string             `json:"arch"`
	Variant    string             `json:"variant"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReleaseManifest struct {
	ReleaseID           uuid.UUID          `json:"release_id"`
	AttemptID           uuid.UUID          `json:"attempt_id"`
	ManifestBlobSha256  string             `json:"manifest_blob_sha256"`
	SignatureBlobSha256 string             `json:"signature_blob_sha256"`
	KeyID               string             `json:"key_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID             uuid.UUID          `json:"id"`
	Key            string             `json:"key"`
	DisplayName    string             `json:"display_name"`
	RepositoryType string             `json:"repository_type"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ServiceAccount struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SigningKey struct {
	KeyID       string             `json:"key_id"`
	Algorithm   string             `json:"algorithm"`
	PublicKey   []byte             `json:"public_key"`
	Fingerprint string             `json:"fingerprint"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UploadSession struct {
	ID                 uuid.UUID          `json:"id"`
	RepositoryID       uuid.UUID          `json:"repository_id"`
	LogicalPath        string             `json:"logical_path"`
	StagingKey         string             `json:"staging_key"`
	State              string             `json:"state"`
	LeaseOwner         uuid.UUID          `json:"lease_owner"`
	LeaseGeneration    int64              `json:"lease_generation"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	HardDeadline       pgtype.Timestamptz `json:"hard_deadline"`
	LastHeartbeatAt    pgtype.Timestamptz `json:"last_heartbeat_at"`
	Sha256             *string            `json:"sha256"`
	Size               *int64             `json:"size"`
	CleanupCompletedAt pgtype.Timestamptz `json:"cleanup_completed_at"`
	CreatedBy          uuid.UUID          `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}
