// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    slug,
    package_id,
    display_name,
    description,
    command_name,
    created_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, package_id, display_name, description, command_name, install_key, previous_install_key, previous_install_key_expires_at, created_by, created_at, updated_at
`

type CreateProductParams struct {
	Slug        string    `json:"slug"`
	PackageID   uuid.UUID `json:"package_id"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	CommandName string    `json:"command_name"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.PackageID,
		arg.DisplayName,
		arg.Description,
		arg.CommandName,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageID,
		&i.DisplayName,
		&i.Description,
		&i.CommandName,
		&i.InstallKey,
		&i.PreviousInstallKey,
		&i.PreviousInstallKeyExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureCLIRepository = `-- name: EnsureCLIRepository :one
INSERT INTO repositories (key, display_name, created_by)
VALUES ('cli-releases', 'CLI Releases', $1)
ON CONFLICT (key) DO UPDATE
SET key = repositories.key
RETURNING id, key, display_name, repository_type, created_by, created_at
`

func (q *Queries) EnsureCLIRepository(ctx context.Context, createdBy uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, ensureCLIRepository, createdBy)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.RepositoryType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const ensureProductChannel = `-- name: EnsureProductChannel :one
INSERT INTO channels (package_id, name)
VALUES ($1, $2)
ON CONFLICT (package_id, name) DO UPDATE
SET name = channels.name
RETURNING id, package_id, name, current_release_id, created_at
`

type EnsureProductChannelParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Name      string    `json:"name"`
}

func (q *Queries) EnsureProductChannel(ctx context.Context, arg EnsureProductChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, ensureProductChannel, arg.PackageID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.CurrentReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const ensureProductPackage = `-- name: EnsureProductPackage :one
INSERT INTO packages (repository_id, name, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (repository_id, name) DO UPDATE
SET name = packages.name
RETURNING id, repository_id, name, created_by, created_at
`

type EnsureProductPackageParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Name         string    `json:"name"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) EnsureProductPackage(ctx context.Context, arg EnsureProductPackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, ensureProductPackage, arg.RepositoryID, arg.Name, arg.CreatedBy)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByInstallKey = `-- name: GetProductByInstallKey :one
SELECT product.id,
       product.slug,
       product.package_id,
       product.display_name,
       product.description,
       product.command_name,
       product.install_key,
       product.created_by,
       product.created_at,
       product.updated_at,
       package.repository_id,
       repository.key AS repository_key,
       package.name AS package_name,
       stable_release.version AS current_stable_version,
       stable_release.published_at AS published_at,
       COALESCE((
           SELECT jsonb_agg(
               jsonb_build_object(
                   'os', platform.os,
                   'arch', platform.arch,
                   'variant', platform.variant,
                   'strategy', platform.strategy,
                   'format', platform.format
               )
               ORDER BY platform.os, platform.arch, platform.variant, platform.strategy, platform.format
           )
           FROM (
               SELECT DISTINCT release_artifact.os,
                               release_artifact.arch,
                               release_artifact.variant,
                               COALESCE(release_artifact.install_spec ->> 'strategy', '') AS strategy,
                               COALESCE(release_artifact.install_spec ->> 'format', '') AS format
               FROM release_artifacts release_artifact
               WHERE release_artifact.release_id = stable_release.id
                 AND release_artifact.role = 'binary'
                 AND release_artifact.install_spec <> '{}'::jsonb
           ) platform
       ), '[]'::jsonb)::text AS platforms_json
FROM products product
JOIN packages package ON package.id = product.package_id
JOIN repositories repository ON repository.id = package.repository_id
LEFT JOIN channels stable_channel
       ON stable_channel.package_id = package.id
      AND stable_channel.name = 'stable'
LEFT JOIN releases stable_release
       ON stable_release.id = stable_channel.current_release_id
      AND stable_release.state = 'published'
WHERE product.install_key = $1
   OR (
       product.previous_install_key = $1
       AND product.previous_install_key_expires_at > now()
   )
`

type GetProductByInstallKeyRow struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	PackageID            uuid.UUID          `json:"package_id"`
	DisplayName          string             `json:"display_name"`
	Description          string             `json:"description"`
	CommandName          string             `json:"command_name"`
	InstallKey           uuid.UUID          `json:"install_key"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RepositoryID         uuid.UUID          `json:"repository_id"`
	RepositoryKey        string             `json:"repository_key"`
	PackageName          string             `json:"package_name"`
	CurrentStableVersion *string            `json:"current_stable_version"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	PlatformsJson        string             `json:"platforms_json"`
}

func (q *Queries) GetProductByInstallKey(ctx context.Context, installKey uuid.UUID) (GetProductByInstallKeyRow, error) {
	row := q.db.QueryRow(ctx, getProductByInstallKey, installKey)
	var i GetProductByInstallKeyRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageID,
		&i.DisplayName,
		&i.Description,
		&i.CommandName,
		&i.InstallKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryID,
		&i.RepositoryKey,
		&i.PackageName,
		&i.CurrentStableVersion,
		&i.PublishedAt,
		&i.PlatformsJson,
	)
	return i, err
}

const getProductByPackageID = `-- name: GetProductByPackageID :one
SELECT id, slug, package_id, display_name, description, command_name, install_key, previous_install_key, previous_install_key_expires_at, created_by, created_at, updated_at
FROM products
WHERE package_id = $1
`

func (q *Queries) GetProductByPackageID(ctx context.Context, packageID uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByPackageID, packageID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageID,
		&i.DisplayName,
		&i.Description,
		&i.CommandName,
		&i.InstallKey,
		&i.PreviousInstallKey,
		&i.PreviousInstallKeyExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleProductBySlug = `-- name: GetVisibleProductBySlug :one
SELECT product.id,
       product.slug,
       product.package_id,
       product.display_name,
       product.description,
       product.command_name,
       product.install_key,
       product.created_by,
       product.created_at,
       product.updated_at,
       package.repository_id,
       repository.key AS repository_key,
       package.name AS package_name,
       stable_release.version AS current_stable_version,
       stable_release.published_at AS published_at,
       COALESCE((
           SELECT jsonb_agg(
               jsonb_build_object(
                   'os', platform.os,
                   'arch', platform.arch,
                   'variant', platform.variant,
                   'strategy', platform.strategy,
                   'format', platform.format
               )
               ORDER BY platform.os, platform.arch, platform.variant, platform.strategy, platform.format
           )
           FROM (
               SELECT DISTINCT release_artifact.os,
                               release_artifact.arch,
                               release_artifact.variant,
                               COALESCE(release_artifact.install_spec ->> 'strategy', '') AS strategy,
                               COALESCE(release_artifact.install_spec ->> 'format', '') AS format
               FROM release_artifacts release_artifact
               WHERE release_artifact.release_id = stable_release.id
                 AND release_artifact.role = 'binary'
                 AND release_artifact.install_spec <> '{}'::jsonb
           ) platform
       ), '[]'::jsonb)::text AS platforms_json
FROM products product
JOIN packages package ON package.id = product.package_id
JOIN repositories repository ON repository.id = package.repository_id
LEFT JOIN channels stable_channel
       ON stable_channel.package_id = package.id
      AND stable_channel.name = 'stable'
LEFT JOIN releases stable_release
       ON stable_release.id = stable_channel.current_release_id
      AND stable_release.state = 'published'
WHERE product.slug = $1
  AND (
      $2::boolean
      OR package.repository_id = ANY($3::uuid[])
  )
`

type GetVisibleProductBySlugParams struct {
	Slug          string      `json:"slug"`
	IncludeAll    bool        `json:"include_all"`
	RepositoryIds []uuid.UUID `json:"repository_ids"`
}

type GetVisibleProductBySlugRow struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	PackageID            uuid.UUID          `json:"package_id"`
	DisplayName          string             `json:"display_name"`
	Description          string             `json:"description"`
	CommandName          string             `json:"command_name"`
	InstallKey           uuid.UUID          `json:"install_key"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RepositoryID         uuid.UUID          `json:"repository_id"`
	RepositoryKey        string             `json:"repository_key"`
	PackageName          string             `json:"package_name"`
	CurrentStableVersion *string            `json:"current_stable_version"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	PlatformsJson        string             `json:"platforms_json"`
}

func (q *Queries) GetVisibleProductBySlug(ctx context.Context, arg GetVisibleProductBySlugParams) (GetVisibleProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getVisibleProductBySlug, arg.Slug, arg.IncludeAll, arg.RepositoryIds)
	var i GetVisibleProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageID,
		&i.DisplayName,
		&i.Description,
		&i.CommandName,
		&i.InstallKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryID,
		&i.RepositoryKey,
		&i.PackageName,
		&i.CurrentStableVersion,
		&i.PublishedAt,
		&i.PlatformsJson,
	)
	return i, err
}

const listVisibleProducts = `-- name: ListVisibleProducts :many
SELECT product.id,
       product.slug,
       product.package_id,
       product.display_name,
       product.description,
       product.command_name,
       product.install_key,
       product.created_by,
       product.created_at,
       product.updated_at,
       package.repository_id,
       repository.key AS repository_key,
       package.name AS package_name,
       stable_release.version AS current_stable_version,
       stable_release.published_at AS published_at,
       COALESCE((
           SELECT jsonb_agg(
               jsonb_build_object(
                   'os', platform.os,
                   'arch', platform.arch,
                   'variant', platform.variant,
                   'strategy', platform.strategy,
                   'format', platform.format
               )
               ORDER BY platform.os, platform.arch, platform.variant, platform.strategy, platform.format
           )
           FROM (
               SELECT DISTINCT release_artifact.os,
                               release_artifact.arch,
                               release_artifact.variant,
                               COALESCE(release_artifact.install_spec ->> 'strategy', '') AS strategy,
                               COALESCE(release_artifact.install_spec ->> 'format', '') AS format
               FROM release_artifacts release_artifact
               WHERE release_artifact.release_id = stable_release.id
                 AND release_artifact.role = 'binary'
                 AND release_artifact.install_spec <> '{}'::jsonb
           ) platform
       ), '[]'::jsonb)::text AS platforms_json
FROM products product
JOIN packages package ON package.id = product.package_id
JOIN repositories repository ON repository.id = package.repository_id
LEFT JOIN channels stable_channel
       ON stable_channel.package_id = package.id
      AND stable_channel.name = 'stable'
LEFT JOIN releases stable_release
       ON stable_release.id = stable_channel.current_release_id
      AND stable_release.state = 'published'
WHERE (
      $1::boolean
      OR package.repository_id = ANY($2::uuid[])
  )
  AND (
      $3::text = ''
      OR product.slug > $3::text
  )
ORDER BY product.slug
LIMIT $4
`

type ListVisibleProductsParams struct {
	IncludeAll    bool        `json:"include_all"`
	RepositoryIds []uuid.UUID `json:"repository_ids"`
	AfterSlug     string      `json:"after_slug"`
	PageLimit     int32       `json:"page_limit"`
}

type ListVisibleProductsRow struct {
	ID                   uuid.UUID          `json:"id"`
	Slug                 string             `json:"slug"`
	PackageID            uuid.UUID          `json:"package_id"`
	DisplayName          string             `json:"display_name"`
	Description          string             `json:"description"`
	CommandName          string             `json:"command_name"`
	InstallKey           uuid.UUID          `json:"install_key"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	RepositoryID         uuid.UUID          `json:"repository_id"`
	RepositoryKey        string             `json:"repository_key"`
	PackageName          string             `json:"package_name"`
	CurrentStableVersion *string            `json:"current_stable_version"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	PlatformsJson        string             `json:"platforms_json"`
}

func (q *Queries) ListVisibleProducts(ctx context.Context, arg ListVisibleProductsParams) ([]ListVisibleProductsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleProducts,
		arg.IncludeAll,
		arg.RepositoryIds,
		arg.AfterSlug,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleProductsRow{}
	for rows.Next() {
		var i ListVisibleProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PackageID,
			&i.DisplayName,
			&i.Description,
			&i.CommandName,
			&i.InstallKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryID,
			&i.RepositoryKey,
			&i.PackageName,
			&i.CurrentStableVersion,
			&i.PublishedAt,
			&i.PlatformsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateProductInstallKey = `-- name: RotateProductInstallKey :one
UPDATE products
SET previous_install_key = install_key,
    previous_install_key_expires_at = now() + interval '30 days',
    install_key = gen_random_uuid(),
    updated_at = now()
WHERE slug = $1
RETURNING id, slug, package_id, display_name, description, command_name, install_key, previous_install_key, previous_install_key_expires_at, created_by, created_at, updated_at
`

func (q *Queries) RotateProductInstallKey(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, rotateProductInstallKey, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PackageID,
		&i.DisplayName,
		&i.Description,
		&i.CommandName,
		&i.InstallKey,
		&i.PreviousInstallKey,
		&i.PreviousInstallKeyExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
