// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abortPublishAttemptToDraft = `-- name: AbortPublishAttemptToDraft :execrows
WITH aborted_attempt AS (
    UPDATE publish_attempts
    SET state = 'aborted',
        failure_code = $4,
        updated_at = $5
    WHERE id = $1
      AND lease_owner = $2
      AND lease_generation = $3
      AND state = 'active'
      AND NOT storage_completed
      AND manifest_sha256 IS NULL
      AND signature_sha256 IS NULL
    RETURNING release_id
)
UPDATE releases r
SET state = 'draft',
    current_attempt_id = NULL,
    failure_code = NULL,
    updated_at = $5
FROM aborted_attempt a
WHERE r.id = a.release_id AND r.current_attempt_id = $1
`

type AbortPublishAttemptToDraftParams struct {
	CurrentAttemptID *uuid.UUID         `json:"current_attempt_id"`
	LeaseOwner       uuid.UUID          `json:"lease_owner"`
	LeaseGeneration  int64              `json:"lease_generation"`
	FailureCode      *string            `json:"failure_code"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AbortPublishAttemptToDraft(ctx context.Context, arg AbortPublishAttemptToDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, abortPublishAttemptToDraft,
		arg.CurrentAttemptID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.FailureCode,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addReleaseArtifact = `-- name: AddReleaseArtifact :one
INSERT INTO release_artifacts (release_id, artifact_id, os, arch, variant, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, release_id, artifact_id, os, arch, variant, role, created_at
`

type AddReleaseArtifactParams struct {
	ReleaseID  uuid.UUID `json:"release_id"`
	ArtifactID uuid.UUID `json:"artifact_id"`
	Os         string    `json:"os"`
	Arch       string    `json:"arch"`
	Variant    string    `json:"variant"`
	Role       string    `json:"role"`
}

func (q *Queries) AddReleaseArtifact(ctx context.Context, arg AddReleaseArtifactParams) (ReleaseArtifact, error) {
	row := q.db.QueryRow(ctx, addReleaseArtifact,
		arg.ReleaseID,
		arg.ArtifactID,
		arg.Os,
		arg.Arch,
		arg.Variant,
		arg.Role,
	)
	var i ReleaseArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ArtifactID,
		&i.Os,
		&i.Arch,
		&i.Variant,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const cancelDraftRelease = `-- name: CancelDraftRelease :execrows
DELETE FROM releases
WHERE id = $1 AND state = 'draft'
`

func (q *Queries) CancelDraftRelease(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelDraftRelease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPublishAttempt = `-- name: CreatePublishAttempt :one
INSERT INTO publish_attempts (
    id,
    release_id,
    idempotency_record_id,
    actor_token_id,
    request_id,
    published_at,
    snapshot,
    snapshot_sha256,
    key_id,
    lease_owner,
    lease_generation,
    lease_expires_at,
    state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 0, $11, 'active')
RETURNING id, release_id, idempotency_record_id, actor_token_id, request_id, published_at, snapshot, snapshot_sha256, key_id, lease_owner, lease_generation, lease_expires_at, state, storage_completed, manifest_sha256, signature_sha256, failure_code, retry_count, next_retry_at, created_at, updated_at
`

type CreatePublishAttemptParams struct {
	ID                  uuid.UUID          `json:"id"`
	ReleaseID           uuid.UUID          `json:"release_id"`
	IdempotencyRecordID *uuid.UUID         `json:"idempotency_record_id"`
	ActorTokenID        uuid.UUID          `json:"actor_token_id"`
	RequestID           string             `json:"request_id"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	Snapshot            []byte             `json:"snapshot"`
	SnapshotSha256      string             `json:"snapshot_sha256"`
	KeyID               string             `json:"key_id"`
	LeaseOwner          uuid.UUID          `json:"lease_owner"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) CreatePublishAttempt(ctx context.Context, arg CreatePublishAttemptParams) (PublishAttempt, error) {
	row := q.db.QueryRow(ctx, createPublishAttempt,
		arg.ID,
		arg.ReleaseID,
		arg.IdempotencyRecordID,
		arg.ActorTokenID,
		arg.RequestID,
		arg.PublishedAt,
		arg.Snapshot,
		arg.SnapshotSha256,
		arg.KeyID,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
	)
	var i PublishAttempt
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.IdempotencyRecordID,
		&i.ActorTokenID,
		&i.RequestID,
		&i.PublishedAt,
		&i.Snapshot,
		&i.SnapshotSha256,
		&i.KeyID,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.State,
		&i.StorageCompleted,
		&i.ManifestSha256,
		&i.SignatureSha256,
		&i.FailureCode,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (package_id, version, state, created_by)
VALUES ($1, $2, 'draft', $3)
RETURNING id, package_id, version, state, current_attempt_id, published_at, failure_code, created_by, created_at, updated_at
`

type CreateReleaseParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Version   string    `json:"version"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease, arg.PackageID, arg.Version, arg.CreatedBy)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.State,
		&i.CurrentAttemptID,
		&i.PublishedAt,
		&i.FailureCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fencePublishAttempt = `-- name: FencePublishAttempt :execrows
UPDATE publish_attempts
SET updated_at = $4
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type FencePublishAttemptParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FencePublishAttempt(ctx context.Context, arg FencePublishAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, fencePublishAttempt,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizePublishedRelease = `-- name: FinalizePublishedRelease :execrows
WITH fenced_attempt AS (
    UPDATE publish_attempts
    SET state = 'completed',
        updated_at = $4
    WHERE id = $1
      AND lease_owner = $2
      AND lease_generation = $3
      AND state = 'active'
      AND storage_completed
    RETURNING release_id, manifest_sha256, signature_sha256, key_id, published_at
)
UPDATE releases r
SET state = 'published',
    published_at = a.published_at,
    failure_code = NULL,
    updated_at = $4
FROM fenced_attempt a
WHERE r.id = a.release_id
  AND r.current_attempt_id = $1
  AND r.state = 'publishing'
`

type FinalizePublishedReleaseParams struct {
	CurrentAttemptID *uuid.UUID         `json:"current_attempt_id"`
	LeaseOwner       uuid.UUID          `json:"lease_owner"`
	LeaseGeneration  int64              `json:"lease_generation"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinalizePublishedRelease(ctx context.Context, arg FinalizePublishedReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizePublishedRelease,
		arg.CurrentAttemptID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublishAttempt = `-- name: GetPublishAttempt :one
SELECT id, release_id, idempotency_record_id, actor_token_id, request_id, published_at, snapshot, snapshot_sha256, key_id, lease_owner, lease_generation, lease_expires_at, state, storage_completed, manifest_sha256, signature_sha256, failure_code, retry_count, next_retry_at, created_at, updated_at
FROM publish_attempts
WHERE id = $1
`

func (q *Queries) GetPublishAttempt(ctx context.Context, id uuid.UUID) (PublishAttempt, error) {
	row := q.db.QueryRow(ctx, getPublishAttempt, id)
	var i PublishAttempt
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.IdempotencyRecordID,
		&i.ActorTokenID,
		&i.RequestID,
		&i.PublishedAt,
		&i.Snapshot,
		&i.SnapshotSha256,
		&i.KeyID,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.State,
		&i.StorageCompleted,
		&i.ManifestSha256,
		&i.SignatureSha256,
		&i.FailureCode,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishReleaseContext = `-- name: GetPublishReleaseContext :one
SELECT r.id AS release_id,
       r.version,
       p.id AS package_id,
       p.name AS package_name,
       repo.id AS repository_id,
       repo.key AS repository_key
FROM releases r
JOIN packages p ON p.id = r.package_id
JOIN repositories repo ON repo.id = p.repository_id
WHERE r.id = $1
`

type GetPublishReleaseContextRow struct {
	ReleaseID     uuid.UUID `json:"release_id"`
	Version       string    `json:"version"`
	PackageID     uuid.UUID `json:"package_id"`
	PackageName   string    `json:"package_name"`
	RepositoryID  uuid.UUID `json:"repository_id"`
	RepositoryKey string    `json:"repository_key"`
}

func (q *Queries) GetPublishReleaseContext(ctx context.Context, id uuid.UUID) (GetPublishReleaseContextRow, error) {
	row := q.db.QueryRow(ctx, getPublishReleaseContext, id)
	var i GetPublishReleaseContextRow
	err := row.Scan(
		&i.ReleaseID,
		&i.Version,
		&i.PackageID,
		&i.PackageName,
		&i.RepositoryID,
		&i.RepositoryKey,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT id, package_id, version, state, current_attempt_id, published_at, failure_code, created_by, created_at, updated_at
FROM releases
WHERE id = $1
`

func (q *Queries) GetReleaseByID(ctx context.Context, id uuid.UUID) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.State,
		&i.CurrentAttemptID,
		&i.PublishedAt,
		&i.FailureCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReleaseByVersion = `-- name: GetReleaseByVersion :one
SELECT id, package_id, version, state, current_attempt_id, published_at, failure_code, created_by, created_at, updated_at
FROM releases
WHERE package_id = $1 AND version = $2
`

type GetReleaseByVersionParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Version   string    `json:"version"`
}

func (q *Queries) GetReleaseByVersion(ctx context.Context, arg GetReleaseByVersionParams) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByVersion, arg.PackageID, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.State,
		&i.CurrentAttemptID,
		&i.PublishedAt,
		&i.FailureCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReleaseForUpdate = `-- name: GetReleaseForUpdate :one
SELECT id, package_id, version, state, current_attempt_id, published_at, failure_code, created_by, created_at, updated_at
FROM releases
WHERE package_id = $1 AND version = $2
FOR UPDATE
`

type GetReleaseForUpdateParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Version   string    `json:"version"`
}

func (q *Queries) GetReleaseForUpdate(ctx context.Context, arg GetReleaseForUpdateParams) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseForUpdate, arg.PackageID, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.State,
		&i.CurrentAttemptID,
		&i.PublishedAt,
		&i.FailureCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReleaseManifest = `-- name: GetReleaseManifest :one
SELECT rm.release_id, rm.attempt_id, rm.manifest_blob_sha256, rm.signature_blob_sha256, rm.key_id, rm.created_at, mb.object_key AS manifest_object_key, sb.object_key AS signature_object_key
FROM release_manifests rm
JOIN blobs mb ON mb.sha256 = rm.manifest_blob_sha256
JOIN blobs sb ON sb.sha256 = rm.signature_blob_sha256
WHERE rm.release_id = $1
`

type GetReleaseManifestRow struct {
	ReleaseID           uuid.UUID          `json:"release_id"`
	AttemptID           uuid.UUID          `json:"attempt_id"`
	ManifestBlobSha256  string             `json:"manifest_blob_sha256"`
	SignatureBlobSha256 string             `json:"signature_blob_sha256"`
	KeyID               string             `json:"key_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ManifestObjectKey   string             `json:"manifest_object_key"`
	SignatureObjectKey  string             `json:"signature_object_key"`
}

func (q *Queries) GetReleaseManifest(ctx context.Context, releaseID uuid.UUID) (GetReleaseManifestRow, error) {
	row := q.db.QueryRow(ctx, getReleaseManifest, releaseID)
	var i GetReleaseManifestRow
	err := row.Scan(
		&i.ReleaseID,
		&i.AttemptID,
		&i.ManifestBlobSha256,
		&i.SignatureBlobSha256,
		&i.KeyID,
		&i.CreatedAt,
		&i.ManifestObjectKey,
		&i.SignatureObjectKey,
	)
	return i, err
}

const insertReleaseManifest = `-- name: InsertReleaseManifest :one
INSERT INTO release_manifests (
    release_id,
    attempt_id,
    manifest_blob_sha256,
    signature_blob_sha256,
    key_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING release_id, attempt_id, manifest_blob_sha256, signature_blob_sha256, key_id, created_at
`

type InsertReleaseManifestParams struct {
	ReleaseID           uuid.UUID `json:"release_id"`
	AttemptID           uuid.UUID `json:"attempt_id"`
	ManifestBlobSha256  string    `json:"manifest_blob_sha256"`
	SignatureBlobSha256 string    `json:"signature_blob_sha256"`
	KeyID               string    `json:"key_id"`
}

func (q *Queries) InsertReleaseManifest(ctx context.Context, arg InsertReleaseManifestParams) (ReleaseManifest, error) {
	row := q.db.QueryRow(ctx, insertReleaseManifest,
		arg.ReleaseID,
		arg.AttemptID,
		arg.ManifestBlobSha256,
		arg.SignatureBlobSha256,
		arg.KeyID,
	)
	var i ReleaseManifest
	err := row.Scan(
		&i.ReleaseID,
		&i.AttemptID,
		&i.ManifestBlobSha256,
		&i.SignatureBlobSha256,
		&i.KeyID,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoverablePublishAttemptIDs = `-- name: ListRecoverablePublishAttemptIDs :many
SELECT id
FROM publish_attempts
WHERE state = 'active'
  AND lease_expires_at < $1::timestamptz
  AND (next_retry_at IS NULL OR next_retry_at <= $1::timestamptz)
  AND retry_count <= 10
ORDER BY lease_expires_at, id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListRecoverablePublishAttemptIDsParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	BatchSize int32              `json:"batch_size"`
}

func (q *Queries) ListRecoverablePublishAttemptIDs(ctx context.Context, arg ListRecoverablePublishAttemptIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRecoverablePublishAttemptIDs, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseArtifacts = `-- name: ListReleaseArtifacts :many
SELECT ra.id, ra.release_id, ra.artifact_id, ra.os, ra.arch, ra.variant, ra.role, ra.created_at, a.repository_id, a.logical_path, a.blob_sha256, a.media_type, a.filename,
       a.properties, a.created_by AS artifact_created_by, a.created_at AS artifact_created_at,
       b.size, b.state AS blob_state
FROM release_artifacts ra
JOIN artifacts a ON a.id = ra.artifact_id
JOIN blobs b ON b.sha256 = a.blob_sha256
WHERE ra.release_id = $1
ORDER BY ra.os, ra.arch, ra.variant, ra.role, a.logical_path
`

type ListReleaseArtifactsRow struct {
	ID                uuid.UUID          `json:"id"`
	ReleaseID         uuid.UUID          `json:"release_id"`
	ArtifactID        uuid.UUID          `json:"artifact_id"`
	Os                string             `json:"os"`
	Arch              string             `json:"arch"`
	Variant           string             `json:"variant"`
	Role              string             `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RepositoryID      uuid.UUID          `json:"repository_id"`
	LogicalPath       string             `json:"logical_path"`
	BlobSha256        string             `json:"blob_sha256"`
	MediaType         string             `json:"media_type"`
	Filename          string             `json:"filename"`
	Properties        []byte             `json:"properties"`
	ArtifactCreatedBy uuid.UUID          `json:"artifact_created_by"`
	ArtifactCreatedAt pgtype.Timestamptz `json:"artifact_created_at"`
	Size              int64              `json:"size"`
	BlobState         string             `json:"blob_state"`
}

func (q *Queries) ListReleaseArtifacts(ctx context.Context, releaseID uuid.UUID) ([]ListReleaseArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listReleaseArtifacts, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseArtifactsRow{}
	for rows.Next() {
		var i ListReleaseArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.ArtifactID,
			&i.Os,
			&i.Arch,
			&i.Variant,
			&i.Role,
			&i.CreatedAt,
			&i.RepositoryID,
			&i.LogicalPath,
			&i.BlobSha256,
			&i.MediaType,
			&i.Filename,
			&i.Properties,
			&i.ArtifactCreatedBy,
			&i.ArtifactCreatedAt,
			&i.Size,
			&i.BlobState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, package_id, version, state, current_attempt_id, published_at, failure_code, created_by, created_at, updated_at
FROM releases
WHERE package_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < (
          $2::timestamptz,
          $3::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListReleasesParams struct {
	PackageID      uuid.UUID          `json:"package_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases,
		arg.PackageID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Version,
			&i.State,
			&i.CurrentAttemptID,
			&i.PublishedAt,
			&i.FailureCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublishAttemptFailed = `-- name: MarkPublishAttemptFailed :execrows
WITH failed_attempt AS (
    UPDATE publish_attempts
    SET state = 'failed',
        failure_code = $4,
        updated_at = $5
    WHERE id = $1
      AND lease_owner = $2
      AND lease_generation = $3
      AND state = 'active'
    RETURNING release_id
)
UPDATE releases r
SET state = 'publish_failed',
    failure_code = $4,
    updated_at = $5
FROM failed_attempt a
WHERE r.id = a.release_id AND r.current_attempt_id = $1
`

type MarkPublishAttemptFailedParams struct {
	CurrentAttemptID *uuid.UUID         `json:"current_attempt_id"`
	LeaseOwner       uuid.UUID          `json:"lease_owner"`
	LeaseGeneration  int64              `json:"lease_generation"`
	FailureCode      *string            `json:"failure_code"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkPublishAttemptFailed(ctx context.Context, arg MarkPublishAttemptFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPublishAttemptFailed,
		arg.CurrentAttemptID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.FailureCode,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPublishFailure = `-- name: RecordPublishFailure :execrows
UPDATE publish_attempts
SET failure_code = $4,
    next_retry_at = $5,
    updated_at = $6
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type RecordPublishFailureParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	FailureCode     *string            `json:"failure_code"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RecordPublishFailure(ctx context.Context, arg RecordPublishFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPublishFailure,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.FailureCode,
		arg.NextRetryAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordPublishStorage = `-- name: RecordPublishStorage :execrows
UPDATE publish_attempts
SET storage_completed = true,
    manifest_sha256 = $4,
    signature_sha256 = $5,
    updated_at = $6
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type RecordPublishStorageParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	ManifestSha256  *string            `json:"manifest_sha256"`
	SignatureSha256 *string            `json:"signature_sha256"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RecordPublishStorage(ctx context.Context, arg RecordPublishStorageParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPublishStorage,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.ManifestSha256,
		arg.SignatureSha256,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeReleaseArtifact = `-- name: RemoveReleaseArtifact :execrows
DELETE FROM release_artifacts ra
USING releases r
WHERE ra.id = $1
  AND ra.release_id = r.id
  AND r.id = $2
  AND r.state = 'draft'
`

type RemoveReleaseArtifactParams struct {
	ReleaseArtifactID uuid.UUID `json:"release_artifact_id"`
	ReleaseID         uuid.UUID `json:"release_id"`
}

func (q *Queries) RemoveReleaseArtifact(ctx context.Context, arg RemoveReleaseArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReleaseArtifact, arg.ReleaseArtifactID, arg.ReleaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewPublishLease = `-- name: RenewPublishLease :execrows
UPDATE publish_attempts
SET lease_expires_at = $4,
    updated_at = $4
WHERE id = $1
  AND lease_owner = $2
  AND lease_generation = $3
  AND state = 'active'
`

type RenewPublishLeaseParams struct {
	ID              uuid.UUID          `json:"id"`
	LeaseOwner      uuid.UUID          `json:"lease_owner"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) RenewPublishLease(ctx context.Context, arg RenewPublishLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewPublishLease,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseGeneration,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReleasePublishing = `-- name: SetReleasePublishing :execrows
UPDATE releases
SET state = 'publishing',
    current_attempt_id = $2,
    failure_code = NULL,
    updated_at = $3
WHERE id = $1 AND state = 'draft'
`

type SetReleasePublishingParams struct {
	ID               uuid.UUID          `json:"id"`
	CurrentAttemptID *uuid.UUID         `json:"current_attempt_id"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetReleasePublishing(ctx context.Context, arg SetReleasePublishingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReleasePublishing, arg.ID, arg.CurrentAttemptID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeExpiredPublishAttempt = `-- name: TakeExpiredPublishAttempt :one
UPDATE publish_attempts
SET lease_owner = $1,
    lease_generation = lease_generation + 1,
    lease_expires_at = $2,
    retry_count = LEAST(retry_count + 1, 10),
    updated_at = $3
WHERE id = (
    SELECT id
    FROM publish_attempts
    WHERE state = 'active'
      AND lease_expires_at < $3
      AND (next_retry_at IS NULL OR next_retry_at <= $3)
      AND retry_count <= 10
    ORDER BY lease_expires_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, release_id, idempotency_record_id, actor_token_id, request_id, published_at, snapshot, snapshot_sha256, key_id, lease_owner, lease_generation, lease_expires_at, state, storage_completed, manifest_sha256, signature_sha256, failure_code, retry_count, next_retry_at, created_at, updated_at
`

type TakeExpiredPublishAttemptParams struct {
	LeaseOwner     uuid.UUID          `json:"lease_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) TakeExpiredPublishAttempt(ctx context.Context, arg TakeExpiredPublishAttemptParams) (PublishAttempt, error) {
	row := q.db.QueryRow(ctx, takeExpiredPublishAttempt, arg.LeaseOwner, arg.LeaseExpiresAt, arg.UpdatedAt)
	var i PublishAttempt
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.IdempotencyRecordID,
		&i.ActorTokenID,
		&i.RequestID,
		&i.PublishedAt,
		&i.Snapshot,
		&i.SnapshotSha256,
		&i.KeyID,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.State,
		&i.StorageCompleted,
		&i.ManifestSha256,
		&i.SignatureSha256,
		&i.FailureCode,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takePublishAttemptLease = `-- name: TakePublishAttemptLease :one
UPDATE publish_attempts
SET lease_owner = $2,
    lease_generation = lease_generation + 1,
    lease_expires_at = $4,
    retry_count = LEAST(retry_count + 1, 10),
    updated_at = $3
WHERE id = $1
  AND state = 'active'
  AND lease_expires_at < $3
  AND (next_retry_at IS NULL OR next_retry_at <= $3)
  AND retry_count <= 10
RETURNING id, release_id, idempotency_record_id, actor_token_id, request_id, published_at, snapshot, snapshot_sha256, key_id, lease_owner, lease_generation, lease_expires_at, state, storage_completed, manifest_sha256, signature_sha256, failure_code, retry_count, next_retry_at, created_at, updated_at
`

type TakePublishAttemptLeaseParams struct {
	ID             uuid.UUID          `json:"id"`
	LeaseOwner     uuid.UUID          `json:"lease_owner"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) TakePublishAttemptLease(ctx context.Context, arg TakePublishAttemptLeaseParams) (PublishAttempt, error) {
	row := q.db.QueryRow(ctx, takePublishAttemptLease,
		arg.ID,
		arg.LeaseOwner,
		arg.UpdatedAt,
		arg.LeaseExpiresAt,
	)
	var i PublishAttempt
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.IdempotencyRecordID,
		&i.ActorTokenID,
		&i.RequestID,
		&i.PublishedAt,
		&i.Snapshot,
		&i.SnapshotSha256,
		&i.KeyID,
		&i.LeaseOwner,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.State,
		&i.StorageCompleted,
		&i.ManifestSha256,
		&i.SignatureSha256,
		&i.FailureCode,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
