// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultChannel = `-- name: CreateDefaultChannel :one
INSERT INTO channels (package_id, name)
VALUES ($1, $2)
RETURNING id, package_id, name, current_release_id, created_at
`

type CreateDefaultChannelParams struct {
	PackageID uuid.UUID `json:"package_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateDefaultChannel(ctx context.Context, arg CreateDefaultChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createDefaultChannel, arg.PackageID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.CurrentReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (repository_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, repository_id, name, created_by, created_at
`

type CreatePackageParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Name         string    `json:"name"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage, arg.RepositoryID, arg.Name, arg.CreatedBy)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (key, display_name, created_by)
VALUES ($1, $2, $3)
RETURNING id, key, display_name, repository_type, created_by, created_at
`

type CreateRepositoryParams struct {
	Key         string    `json:"key"`
	DisplayName string    `json:"display_name"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository, arg.Key, arg.DisplayName, arg.CreatedBy)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.RepositoryType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPackageByName = `-- name: GetPackageByName :one
SELECT p.id, p.repository_id, p.name, p.created_by, p.created_at
FROM packages p
JOIN repositories r ON r.id = p.repository_id
WHERE r.key = $1 AND p.name = $2
`

type GetPackageByNameParams struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

func (q *Queries) GetPackageByName(ctx context.Context, arg GetPackageByNameParams) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByName, arg.Key, arg.Name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, key, display_name, repository_type, created_by, created_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.RepositoryType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositoryByKey = `-- name: GetRepositoryByKey :one
SELECT id, key, display_name, repository_type, created_by, created_at FROM repositories WHERE key = $1
`

func (q *Queries) GetRepositoryByKey(ctx context.Context, key string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByKey, key)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.DisplayName,
		&i.RepositoryType,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelsByPackage = `-- name: ListChannelsByPackage :many
SELECT id, package_id, name, current_release_id, created_at
FROM channels
WHERE package_id = $1
ORDER BY name
`

func (q *Queries) ListChannelsByPackage(ctx context.Context, packageID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Name,
			&i.CurrentReleaseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
SELECT p.id, p.repository_id, p.name, p.created_by, p.created_at
FROM packages p
WHERE p.repository_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (p.created_at, p.id) < (
          $2::timestamptz,
          $3::uuid
      )
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4
`

type ListPackagesParams struct {
	RepositoryID   uuid.UUID          `json:"repository_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        uuid.UUID          `json:"after_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]Package, error) {
	rows, err := q.db.Query(ctx, listPackages,
		arg.RepositoryID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, key, display_name, repository_type, created_by, created_at
FROM repositories
WHERE (cardinality($1::uuid[]) = 0 OR id = ANY($1::uuid[]))
  AND ($2::text = '' OR key > $2::text)
ORDER BY key
LIMIT $3
`

type ListRepositoriesParams struct {
	RepositoryIds []uuid.UUID `json:"repository_ids"`
	AfterKey      string      `json:"after_key"`
	PageLimit     int32       `json:"page_limit"`
}

func (q *Queries) ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, arg.RepositoryIds, arg.AfterKey, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.DisplayName,
			&i.RepositoryType,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
