{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifact-repository.fullname" . }}
  labels:
    {{- include "artifact-repository.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  TOKEN_PEPPER: {{ .Values.secrets.tokenPepper | b64enc | quote }}
  IDEMPOTENCY_RESPONSE_KEY: {{ .Values.secrets.idempotencyResponseKey | b64enc | quote }}
{{- end }}
